//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by game.rc
//
#define ICO_ICON                        125
#define FNT_FONT1                       126
#define GFX_IN_MEMORIA_TILE_PICTURE_10  144
#define GFX_IN_MEMORIA_TILE_PICTURE_11  145
#define GFX_IN_MEMORIA_UNFLIPPED_TILE_PICTURE 154
#define GFX_MINI_GAME_FRAME             155
#define GFX_FLIGHT_OF_DOOM_SHIP         162
#define GFX_FLIGHT_OF_DOOM_ASTEROID     163
#define GFX_RELUCTANT_HERO_BACKGROUND   169
#define GFX_STATUS_BAR                  172
#define GFX_COSMIC_SQUIRREL_ACORN       178
#define GFX_REFLUXIVE_PADDLE            180
#define GFX_REFLUXIVE_BOUNCY            181
#define GFX_DEFENDOH_LANDSCAPE          183
#define GFX_REFLUXIVE_BACKGROUND        184
#define GFX_GO                          187
#define GFX_GET_READY                   188
#define GFX_GET_SET                     189
#define GFX_A_DAY_IN_THE_STRIFE_BACKGROUND 203
#define GFX_LEPAR_LAND_TREE             217
#define GFX_LEPAR_LAND_MUD              218
#define GFX_LEPAR_LAND_DEAD_LEPAR       221
#define GFX_LEPAR_LAND_TREASURE         222
#define GFX_DEATHTRAP_BACKGROUND        225
#define GFX_DEATHTRAP_PLAYER_STANDING   226
#define GFX_DEATHTRAP_PLAYER_JUMPING    227
#define GFX_A_DAY_IN_THE_STRIFE_GREEN_ALIEN_00 256
#define GFX_A_DAY_IN_THE_STRIFE_GREEN_ALIEN_01 257
#define GFX_A_DAY_IN_THE_STRIFE_RED_ALIEN_00 258
#define GFX_A_DAY_IN_THE_STRIFE_RED_ALIEN_01 259
#define GFX_A_DAY_IN_THE_STRIFE_SHIELD_00 260
#define GFX_A_DAY_IN_THE_STRIFE_SHIELD_01 261
#define GFX_A_DAY_IN_THE_STRIFE_SHIELD_02 262
#define GFX_A_DAY_IN_THE_STRIFE_SHIELD_03 263
#define GFX_A_DAY_IN_THE_STRIFE_SHIP_00 264
#define GFX_A_DAY_IN_THE_STRIFE_SHIP_01 265
#define GFX_A_DAY_IN_THE_STRIFE_YELLOW_ALIEN_00 266
#define GFX_A_DAY_IN_THE_STRIFE_YELLOW_ALIEN_01 267
#define GFX_COPYCAT_SYMBOL_00           268
#define GFX_COPYCAT_SYMBOL_01           269
#define GFX_COPYCAT_SYMBOL_02           270
#define GFX_COPYCAT_SYMBOL_03           271
#define GFX_COPYCAT_SYMBOL_HIGHLIGHT_00 272
#define GFX_COPYCAT_SYMBOL_HIGHLIGHT_01 273
#define GFX_COPYCAT_SYMBOL_HIGHLIGHT_02 274
#define GFX_COPYCAT_SYMBOL_HIGHLIGHT_03 275
#define GFX_COSMIC_SQUIRREL_SQUIRREL_00 276
#define GFX_COSMIC_SQUIRREL_SQUIRREL_01 277
#define GFX_DEATHTRAP_PLAYER_DIEING_00  278
#define GFX_DEATHTRAP_PLAYER_DIEING_01  279
#define GFX_EXPLOSION_00                280
#define GFX_EXPLOSION_01                281
#define GFX_EXPLOSION_02                282
#define GFX_EXPLOSION_03                283
#define GFX_EXPLOSION_04                284
#define GFX_IN_MEMORIA_TILE_PICTURE_00  285
#define GFX_IN_MEMORIA_TILE_PICTURE_01  286
#define GFX_IN_MEMORIA_TILE_PICTURE_02  287
#define GFX_IN_MEMORIA_TILE_PICTURE_03  288
#define GFX_IN_MEMORIA_TILE_PICTURE_04  289
#define GFX_IN_MEMORIA_TILE_PICTURE_05  290
#define GFX_IN_MEMORIA_TILE_PICTURE_06  291
#define GFX_IN_MEMORIA_TILE_PICTURE_07  292
#define GFX_IN_MEMORIA_TILE_PICTURE_08  293
#define GFX_IN_MEMORIA_TILE_PICTURE_09  294
#define GFX_LEPAR_LAND_LEPAR_00         297
#define GFX_LEPAR_LAND_LEPAR_01         298
#define GFX_LEPAR_LAND_PLAYER_00        299
#define GFX_LEPAR_LAND_PLAYER_01        300
#define GFX_RELUCTANT_HERO_PERSON_00    301
#define GFX_RELUCTANT_HERO_PERSON_01    302
#define GFX_RELUCTANT_HERO_PLAYER_00    303
#define GFX_RELUCTANT_HERO_PLAYER_01    304
#define GFX_MISSILE_00                  305
#define GFX_MISSILE_01                  306
#define SFX_CHOMP                       308
#define SFX_EXPLOSION                   310
#define SFX_DEATH                       313
#define GFX_LOGO_OMNYTEX                315
#define SFX_MISSILE_FIRING              316
#define SFX_SHIP                        317
#define GFX_VIRUS_SYMBOL_2              322
#define GFX_VIRUS_SYMBOL_0              323
#define GFX_VIRUS_SYMBOL_1              324
#define GFX_VIRUS_SYMBOL_SELECTED_2     325
#define GFX_VIRUS_SYMBOL_SELECTED_0     326
#define GFX_VIRUS_SYMBOL_SELECTED_1     327
#define SFX_WIN_1                       328
#define GFX_LEPAR_LAND_PLAYER_STILL     329
#define SFX_ZAP                         330
#define SFX_WIN_2                       331
#define SFX_JUMP                        332
#define SFX_TONE_D                      333
#define SFX_TONE_A                      334
#define SFX_TONE_B                      335
#define SFX_TONE_C                      336
#define SFX_CACHING                     337
#define GFX_GLUTTON_HEAD                338
#define GFX_GLUTTON_BODY                339
#define GFX_GLUTTON_FOOD                340
#define SFX_MOVE                        341
#define SFX_TANK                        342
#define SFX_SPLAT                       343
#define SFX_UNFLIP                      344
#define SFX_NO_MATCH                    345
#define SFX_MISSED                      346
#define SFX_BOUNCE                      347
#define SFX_THANK_YOU                   348
#define GFX_GLUTTON_BACKGROUND          349
#define GFX_ANTIGRAVITATOR_GRAVPIT_00   355
#define GFX_ANTIGRAVITATOR_GRAVPIT_01   356
#define GFX_ANTIGRAVITATOR_GUN          357
#define GFX_ANTIGRAVITATOR_LASER        358
#define GFX_CONQUERROR_BACKGROUND       359
#define GFX_CONQUERROR_BUILDING_1       360
#define GFX_CONQUERROR_BUILDING_1_DESTROYED 361
#define GFX_CONQUERROR_BUILDING_2       362
#define GFX_CONQUERROR_BUILDING_2_DESTROYED 363
#define GFX_CONQUERROR_BUILDING_3       364
#define GFX_CONQUERROR_BUILDING_3_DESTROYED 365
#define GFX_CONQUERROR_BUILDING_4       366
#define GFX_CONQUERROR_BUILDING_4_DESTROYED 367
#define GFX_CONQUERROR_GUN_BOTTOM       368
#define GFX_CONQUERROR_GUN_TOP          369
#define GFX_FAR_OUT_FOWL_EGG_SPLAT      370
#define GFX_FAR_OUT_FOWL_BACKGROUND     371
#define GFX_FAR_OUT_FOWL_CATCHER        372
#define GFX_FAR_OUT_FOWL_EGG            374
#define GFX_CONSOLE_RIGHT               375
#define GFX_CONSOLE_LEFT                376
#define GFX_CONSOLE_MIDDLE              377
#define GFX_LEFT_HAND_UP                378
#define GFX_LEFT_HAND_DOWN              379
#define GFX_LEFT_HAND_LEFT              380
#define GFX_LEFT_HAND_NORMAL            381
#define GFX_LEFT_HAND_RIGHT             382
#define GFX_RIGHT_HAND_UP               383
#define GFX_RIGHT_HAND_DOWN             384
#define GFX_THE_ESCAPE_WALL             385
#define GFX_THE_ESCAPE_DESTPAD          386
#define GFX_THE_ESCAPE_PLAYER_STILL     387
#define GFX_THE_ESCAPE_ROCK             388
#define GFX_LEFT_HAND_DL                389
#define GFX_LEFT_HAND_DR                390
#define GFX_LEFT_HAND_UL                391
#define GFX_LEFT_HAND_UR                392
#define GFX_THE_ESCAPE_ROCK_IN_PLACE    393
#define GFX_DEFENDOH_ALIEN_00           394
#define GFX_DEFENDOH_ALIEN_01           395
#define GFX_DEFENDOH_SHIP_00            396
#define GFX_DEFENDOH_SHIP_01            397
#define GFX_COSMIC_SQUIRREL_ALIEN_00    398
#define GFX_COSMIC_SQUIRREL_ALIEN_01    399
#define GFX_COSMIC_SQUIRREL_COMET_00    400
#define GFX_COSMIC_SQUIRREL_COMET_01    401
#define GFX_ALIEN_BABBLE_BOX            402
#define GFX_ALIEN_BABBLE_ALIEN_LEFT     403
#define GFX_ALIEN_BABBLE_ALIEN_STILL    404
#define GFX_ALIEN_BABBLE_ARROW          405
#define GFX_ALIEN_BABBLE_TARGET         406
#define GFX_THE_REDEYE_ORDER_6          407
#define GFX_THE_REDEYE_ORDER_1          408
#define GFX_THE_REDEYE_ORDER_2          409
#define GFX_THE_REDEYE_ORDER_3          410
#define GFX_THE_REDEYE_ORDER_4          411
#define GFX_THE_REDEYE_ORDER_5          412
#define GFX_THE_REDEYE_ORDER_11         413
#define GFX_THE_REDEYE_ORDER_7          414
#define GFX_THE_REDEYE_ORDER_8          415
#define GFX_THE_REDEYE_ORDER_9          416
#define GFX_THE_REDEYE_ORDER_10         417
#define GFX_THE_REDEYE_ORDER_15         418
#define GFX_THE_REDEYE_ORDER_13         419
#define GFX_THE_REDEYE_ORDER_14         420
#define GFX_THE_REDEYE_ORDER_12         421
#define GFX_FFOPIR_SIRTET_PAEHC_BLOCK   429
#define GFX_ENGINEER_BACKGROUND         432
#define GFX_ENGINEER_DIVERTER_VERTICAL  433
#define GFX_ENGINEER_DIVERTER_DOWN_LEFT 434
#define GFX_ENGINEER_DIVERTER_DOWN_RIGHT 435
#define GFX_ENGINEER_DIVERTER_HORIZONTAL 436
#define GFX_ENGINEER_DIVERTER_UP_LEFT   437
#define GFX_ENGINEER_DIVERTER_UP_RIGHT  438
#define GFX_LOGO_CRACKHEAD              441
#define IDR_MAP_LEVEL_1                 446
#define IDR_DISSOLVE_DAT                449
#define GFX_PLAYER_WALKING_N_01         455
#define GFX_PLAYER_WALKING_E_00         456
#define GFX_PLAYER_WALKING_E_01         457
#define GFX_PLAYER_WALKING_N_00         458
#define GFX_PLAYER_WALKING_S_00         464
#define GFX_PLAYER_WALKING_S_01         465
#define GFX_PLAYER_WALKING_W_01         467
#define GFX_PLAYER_WALKING_W_00         470
#define GFX_ROBOT_DISAPPEARING_APPEARING_04 474
#define GFX_ROBOT_DISAPPEARING_APPEARING_00 475
#define GFX_ROBOT_DISAPPEARING_APPEARING_01 476
#define GFX_ROBOT_DISAPPEARING_APPEARING_02 477
#define GFX_ROBOT_DISAPPEARING_APPEARING_03 478
#define GFX_ROBOT_DISAPPEARING_APPEARING_10 479
#define GFX_ROBOT_DISAPPEARING_APPEARING_05 480
#define GFX_ROBOT_DISAPPEARING_APPEARING_06 481
#define GFX_ROBOT_DISAPPEARING_APPEARING_07 482
#define GFX_ROBOT_DISAPPEARING_APPEARING_08 483
#define GFX_ROBOT_DISAPPEARING_APPEARING_09 484
#define GFX_ROBOT_DISAPPEARING_APPEARING_15 485
#define GFX_ROBOT_DISAPPEARING_APPEARING_12 486
#define GFX_ROBOT_DISAPPEARING_APPEARING_13 487
#define GFX_ROBOT_DISAPPEARING_APPEARING_14 488
#define GFX_ROBOT_STILL_00              506
#define GFX_ROBOT_STILL_01              507
#define GFX_ROBOT_STILL_02              508
#define GFX_ROBOT_STILL_03              509
#define GFX_ROBOT_STILL_04              510
#define GFX_ROBOT_STILL_05              511
#define GFX_ROBOT_STILL_06              512
#define GFX_ROBOT_NEW_TILE_APPEARING_00 513
#define GFX_ROBOT_DISAPPEARING_APPEARING_11 514
#define GFX_FAR_OUT_FOWL_CHICKEN_00     515
#define GFX_FAR_OUT_FOWL_CHICKEN_01     516
#define GFX_ANTIGRAVITATOR_SHIP_05      517
#define GFX_ANTIGRAVITATOR_SHIP_00      518
#define GFX_ANTIGRAVITATOR_SHIP_01      519
#define GFX_ANTIGRAVITATOR_SHIP_02      520
#define GFX_ANTIGRAVITATOR_SHIP_03      521
#define GFX_ANTIGRAVITATOR_SHIP_04      522
#define GFX_MENU_NEW_GAME_1             523
#define GFX_MENU_BOTTOM                 524
#define GFX_MENU_CONTINUE_GAME_0        525
#define GFX_MENU_CONTINUE_GAME_1        526
#define GFX_MENU_CREDITS_0              527
#define GFX_MENU_CREDITS_1              528
#define GFX_MENU_NEW_GAME_0             529
#define GFX_MENU_TOP                    530
#define GFX_MENU_OPTIONS_0              531
#define GFX_MENU_OPTIONS_1              532
#define GFX_MENU_QUIT_0                 533
#define GFX_MENU_QUIT_1                 534
#define GFX_MAIN_MENU_BACKGROUND_TILE   535
#define GFX_MAIN_MENU_TITLE             536
#define GFX_HEART_1                     541
#define GFX_HEART_2                     542
#define IDR_MAP_LEVEL_5                 545
#define IDR_MAP_LEVEL_2                 546
#define IDR_MAP_LEVEL_3                 547
#define IDR_MAP_LEVEL_4                 548
#define SFX_GAME_EXIT_SOUND             549
#define SFX_MISC_2                      550
#define SFX_MISC_1                      551
#define GFX_GAME_DONE_ON                552
#define GFX_GAME_DONE_OFF               553
#define SFX_MISC_5                      568
#define SFX_MISC_3                      569
#define SFX_MISC_4                      570
#define GFX_SS_DEATHTRAP                571
#define GFX_SS_A_DAY_IN_THE_STRIFE      572
#define GFX_SS_ALIEN_BABBLE             573
#define GFX_SS_ANTIGRAVITATOR           574
#define GFX_SS_CONQUERROR               575
#define GFX_SS_COPYCAT                  576
#define GFX_SS_COSMIC_SQUIRREL          577
#define GFX_SS_IN_MEMORIA               578
#define GFX_SS_DEFENDOH                 579
#define GFX_SS_ENGINEER                 580
#define GFX_SS_FAR_OUT_FOWL             581
#define GFX_SS_FFOPIR_SIRTET_PAEHC      582
#define GFX_SS_FLIGHT_OF_DOOM           583
#define GFX_SS_GLUTTON                  584
#define GFX_SS_LEPAR_LAND               585
#define GFX_SS_REFLUXIVE                586
#define GFX_SS_RELUCTANT_HERO           587
#define GFX_SS_THE_BOGAZ_DERBY          588
#define GFX_SS_THE_ESCAPE               589
#define GFX_SS_THE_REDEYE_ORDER         590
#define GFX_SS_VIRUS                    591
#define GFX_ICON_MINI_GAME_MELEE        592
#define GFX_ICON_ADVENTURE_GAME         593
#define GFX_LOCK                        597
#define GFX_ENGINEER_PARTICLE4_01       602
#define GFX_ENGINEER_PARTICLE1_00       603
#define GFX_ENGINEER_PARTICLE1_01       604
#define GFX_ENGINEER_PARTICLE2_00       605
#define GFX_ENGINEER_PARTICLE2_01       606
#define GFX_ENGINEER_PARTICLE3_00       607
#define GFX_ENGINEER_PARTICLE3_01       608
#define GFX_ENGINEER_PARTICLE4_00       609
#define GFX_TITLE_06                    610
#define GFX_TITLE_01                    611
#define GFX_TITLE_02                    612
#define GFX_TITLE_03                    613
#define GFX_TITLE_04                    614
#define GFX_TITLE_05                    615
#define GFX_TITLE_12                    616
#define GFX_TITLE_07                    617
#define GFX_TITLE_08                    618
#define GFX_TITLE_09                    619
#define GFX_TITLE_10                    620
#define GFX_TITLE_11                    621
#define GFX_TITLE_18                    622
#define GFX_TITLE_13                    623
#define GFX_TITLE_14                    624
#define GFX_TITLE_15                    625
#define GFX_TITLE_16                    626
#define GFX_TITLE_17                    627
#define GFX_TITLE_KANG                  628
#define SFX_TITLE_KRELMAC               629
#define SFX_TITLE_BACKGROUND            630
#define SFX_TITLE_CRASH                 631
#define SFX_TITLE_GENTOO                632
#define GFX_MENU_INSTRUCTIONS_1         633
#define GFX_MENU_INSTRUCTIONS_0         634
#define GFX_INS_PREV_1                  635
#define GFX_INS_NEXT_0                  636
#define GFX_INS_NEXT_1                  637
#define GFX_INS_PREV_0                  638
#define SFX_INS_ARROW                   639
#define GFX_POPUP_BORDER                640
#define OSS_PLAYER_DIED                 648
#define GFX_DIVIDER_00                  649
#define GFX_POPUP_BORDER_BIG            652
#define GFX_CAPTIVE_1_EXPRESSION_5      653
#define GFX_CAPTIVE_1_EXPRESSION_1      654
#define GFX_CAPTIVE_1_EXPRESSION_2      655
#define GFX_CAPTIVE_1_EXPRESSION_3      656
#define GFX_CAPTIVE_1_EXPRESSION_4      657
#define GFX_PLAYER_WALKING_W_02         658
#define GFX_PLAYER_WALKING_E_02         659
#define GFX_PLAYER_WALKING_N_02         660
#define GFX_PLAYER_WALKING_S_02         661
#define GFX_TILE_TELEPORTER_00          662
#define GFX_TILE_CONSOLE_00             663
#define GFX_TILE_LEVEL_1_WALL_W         664
#define GFX_TILE_LEVEL_1_FLOOR_01       665
#define GFX_TILE_LEVEL_1_WALL_BLOCK     666
#define GFX_TILE_LEVEL_1_WALL_E         667
#define GFX_TILE_LEVEL_1_WALL_N         668
#define GFX_TILE_LEVEL_1_WALL_NE        669
#define GFX_TILE_LEVEL_1_WALL_NW        670
#define GFX_TILE_LEVEL_1_WALL_S         671
#define GFX_TILE_LEVEL_1_WALL_SW        672
#define GFX_TILE_LEVEL_1_WALL_SE        673
#define GFX_TILE_LEVEL_2_WALL_NE        674
#define GFX_TILE_LEVEL_2_FLOOR_01       675
#define GFX_TILE_LEVEL_2_WALL_BLOCK     676
#define GFX_TILE_LEVEL_2_WALL_E         677
#define GFX_TILE_LEVEL_2_WALL_N         678
#define GFX_TILE_LEVEL_2_WALL_W         679
#define GFX_TILE_LEVEL_2_WALL_NW        680
#define GFX_TILE_LEVEL_2_WALL_S         681
#define GFX_TILE_LEVEL_2_WALL_SE        682
#define GFX_TILE_LEVEL_2_WALL_SW        683
#define GFX_THE_BOGAZ_DERBY_STREET      685
#define GFX_THE_BOGAZ_DERBY_SIDE        686
#define GFX_THE_BOGAZ_DERBY_PLAYER_01   687
#define GFX_THE_BOGAZ_DERBY_ENEMY_00    688
#define GFX_THE_BOGAZ_DERBY_ENEMY_01    689
#define GFX_THE_BOGAZ_DERBY_PLAYER_00   690
#define IDR_CI_EEGER                    691
#define FNT_FONT1_GREEN                 693
#define GFX_ROBOT_DISAPPEARING_APPEARING_16 694
#define GFX_ROBOT_NEW_TILE_APPEARING_05 695
#define GFX_ROBOT_NEW_TILE_APPEARING_01 696
#define GFX_ROBOT_NEW_TILE_APPEARING_02 697
#define GFX_ROBOT_NEW_TILE_APPEARING_03 698
#define GFX_ROBOT_NEW_TILE_APPEARING_04 699
#define GFX_TILE_LEVEL_3_WALL_NE        711
#define GFX_TILE_LEVEL_3_FLOOR_01       712
#define GFX_TILE_LEVEL_3_WALL_ALONE     713
#define GFX_TILE_LEVEL_3_WALL_BLOCK     714
#define GFX_TILE_LEVEL_3_WALL_E         715
#define GFX_TILE_LEVEL_3_WALL_N         716
#define GFX_TILE_LEVEL_3_WALL_W         717
#define GFX_TILE_LEVEL_3_WALL_NW        718
#define GFX_TILE_LEVEL_3_WALL_S         719
#define GFX_TILE_LEVEL_3_WALL_SE        720
#define GFX_TILE_LEVEL_3_WALL_SW        721
#define GFX_SS_SQUISHEM                 722
#define GFX_SQUISHEM_ALIEN_00           724
#define SFX_UNLOCKCODE                  725
#define GFX_SQUISHEM_ALIEN_01           726
#define GFX_SQUISHEM_ALIEN_02           727
#define GFX_SQUISHEM_ALIEN_03           728
#define GFX_SQUISHEM_ALIEN_04           729
#define GFX_SQUISHEM_ALIEN_05           730
#define GFX_SQUISHEM_RAYV_01            733
#define GFX_SQUISHEM_RAYV_00            734
#define GFX_SQUISHEM_RAYH_01            735
#define GFX_SQUISHEM_RAYH_00            736
#define OSS_THE_ADVENTURE_BEGINS        754
#define OSS_WIN                         755
#define SFX_BEAMMEUP                    756
#define GFX_SS_TROUBLE_IN_LINE_WORLD    758
#define GFX_TROUBLE_IN_LINE_WORLD_SHIP_05 759
#define GFX_TROUBLE_IN_LINE_WORLD_SHIP_00 760
#define GFX_TROUBLE_IN_LINE_WORLD_SHIP_01 761
#define GFX_TROUBLE_IN_LINE_WORLD_SHIP_02 762
#define GFX_TROUBLE_IN_LINE_WORLD_SHIP_03 763
#define GFX_TROUBLE_IN_LINE_WORLD_SHIP_04 764
#define GFX_FFOPIR_SIRTET_PAEHC_BACKGROUND 766
#define GFX_TROUBLE_IN_LINE_WORLD_CROSSHAIRS_GREEN 767
#define GFX_TROUBLE_IN_LINE_WORLD_CROSSHAIRS_RED 768
#define SFX_LASER                       769
#define GFX_MUNCHER_DUDE_BACKGROUND     770
#define GFX_MUNCHER_DUDE_PLAYER_01      771
#define GFX_MUNCHER_DUDE_PLAYER_00      772
#define GFX_MUNCHER_DUDE_PELLET         773
#define GFX_SON_OF_ELIMINATOR_UP        774
#define GFX_SON_OF_ELIMINATOR_DOWN      775
#define GFX_SON_OF_ELIMINATOR_EMPTY     776
#define GFX_SON_OF_ELIMINATOR_DOWN_CURRENT 777
#define GFX_SON_OF_ELIMINATOR_EMPTY_CURRENT 778
#define GFX_SON_OF_ELIMINATOR_UP_CURRENT 779
#define GFX_MUNCHER_DUDE_ALIEN_01       780
#define GFX_MUNCHER_DUDE_ALIEN_00       781
#define SFX_SON_OF_ELIMINATOR_UP        782
#define SFX_SON_OF_ELIMINATOR_DOWN      783
#define SFX_SON_OF_ELIMINATOR_REMOVE    784
#define SFX_MUSIC_THEME                 785
#define GFX_SS_SON_OF_ELIMINATOR        786
#define GFX_SS_MUNCHER_DUDE             787
#define GFX_TILE_LEVEL_5_FLOOR_01       788
#define GFX_TILE_LEVEL_5_WALL_ALONE     789
#define GFX_TILE_LEVEL_5_WALL_W_TJOINT  790
#define GFX_TILE_LEVEL_5_WALL_W         791
#define GFX_TILE_LEVEL_5_WALL_SW        792
#define GFX_TILE_LEVEL_5_WALL_SE        793
#define GFX_TILE_LEVEL_5_WALL_S_TJOINT  794
#define GFX_TILE_LEVEL_5_WALL_S         795
#define GFX_TILE_LEVEL_5_WALL_NW        796
#define GFX_TILE_LEVEL_5_WALL_NE        797
#define GFX_TILE_LEVEL_5_WALL_N_TJOINT  798
#define GFX_TILE_LEVEL_5_WALL_N         799
#define GFX_TILE_LEVEL_5_WALL_E_TJOINT  800
#define GFX_TILE_LEVEL_5_WALL_E         801
#define GFX_TILE_LEVEL_5_WALL_BLOCK     802
#define GFX_TILE_LEVEL_4_WALL_NW        803
#define GFX_TILE_LEVEL_4_FLOOR_01       804
#define GFX_TILE_LEVEL_4_WALL_ALONE     805
#define GFX_TILE_LEVEL_4_WALL_BLOCK     806
#define GFX_TILE_LEVEL_4_WALL_E         807
#define GFX_TILE_LEVEL_4_WALL_N         808
#define GFX_TILE_LEVEL_4_WALL_NE        809
#define GFX_TILE_LEVEL_4_WALL_W         810
#define GFX_TILE_LEVEL_4_WALL_S         811
#define GFX_TILE_LEVEL_4_WALL_SE        812
#define GFX_TILE_LEVEL_4_WALL_SW        813
#define IDR_CI_SULLY                    814
#define IDR_CI_BRENDA_BUBEY             815
#define IDR_CI_CATRINA                  816
#define IDR_CI_FREDERICK_J_SMILEY       817
#define GFX_CAPTIVE_2_EXPRESSION_5      818
#define GFX_CAPTIVE_2_EXPRESSION_1      819
#define GFX_CAPTIVE_2_EXPRESSION_2      820
#define GFX_CAPTIVE_2_EXPRESSION_3      821
#define GFX_CAPTIVE_2_EXPRESSION_4      822
#define GFX_CAPTIVE_3_EXPRESSION_5      823
#define GFX_CAPTIVE_3_EXPRESSION_1      824
#define GFX_CAPTIVE_3_EXPRESSION_2      825
#define GFX_CAPTIVE_3_EXPRESSION_3      826
#define GFX_CAPTIVE_3_EXPRESSION_4      827
#define GFX_CAPTIVE_4_EXPRESSION_5      828
#define GFX_CAPTIVE_4_EXPRESSION_1      829
#define GFX_CAPTIVE_4_EXPRESSION_2      830
#define GFX_CAPTIVE_4_EXPRESSION_3      831
#define GFX_CAPTIVE_4_EXPRESSION_4      832
#define GFX_CAPTIVE_5_EXPRESSION_5      833
#define GFX_CAPTIVE_5_EXPRESSION_1      834
#define GFX_CAPTIVE_5_EXPRESSION_2      835
#define GFX_CAPTIVE_5_EXPRESSION_3      836
#define GFX_CAPTIVE_5_EXPRESSION_4      837
#define GFX_CAPTIVE_EEGER_01            838
#define GFX_CAPTIVE_BRENDA_BUBEY_00     839
#define GFX_CAPTIVE_BRENDA_BUBEY_01     840
#define GFX_CAPTIVE_CATRINA_00          841
#define GFX_CAPTIVE_CATRINA_01          842
#define GFX_CAPTIVE_EEGER_00            843
#define GFX_CAPTIVE_SULLY_01            844
#define GFX_CAPTIVE_FREDERICK_H_SMILEY_00 845
#define GFX_CAPTIVE_FREDERICK_H_SMILEY_01 846
#define GFX_CAPTIVE_SULLY_00            847
#define GFX_TILE_HEALTH                 848
#define GFX_TILE_LEVEL_5_WALL_VERTICAL  849
#define GFX_TILE_LEVEL_5_WALL_HORIZONTAL 850
#define SFX_VOICE_GENTOO_01             885
#define SFX_VOICE_GENTOO_05             889
#define SFX_VOICE_GENTOO_06             890
#define SFX_VOICE_GENTOO_07             891
#define SFX_VOICE_GENTOO_08             892
#define SFX_VOICE_GENTOO_09             893
#define SFX_VOICE_GENTOO_12             896
#define SFX_VOICE_GENTOO_13             897
#define SFX_VOICE_KRELMAC_16            898
#define SFX_VOICE_KRELMAC_15            899
#define SFX_VOICE_KRELMAC_13            901
#define SFX_VOICE_KRELMAC_12            902
#define SFX_VOICE_KRELMAC_08            906
#define SFX_VOICE_KRELMAC_07            907
#define SFX_VOICE_KRELMAC_06            908
#define SFX_VOICE_KRELMAC_05            909
#define SFX_VOICE_KRELMAC_04            910
#define SFX_VOICE_KRELMAC_01            913
#define SFX_VOICE_GENTOO_17             916
#define SFX_VOICE_GENTOO_15             918
#define SFX_BOUNCE_2                    920
#define GFX_SHIP_INTERIOR               921
#define GFX_KRELMAC_01                  922
#define GFX_KRELMAC_02                  923
#define GFX_KRELMAC_03                  924
#define GFX_GENTOO_01                   925
#define GFX_GENTOO_02                   926
#define GFX_GENTOO_03                   927
#define GFX_GENTOO_04                   928
#define GFX_GENTOO_05                   929
#define GFX_GENTOO_06                   931
#define GFX_KRELMAC_04                  935
#define GFX_KRELMAC_05                  936
#define GFX_KRELMAC_06                  937
#define GFX_ALIEN_BABBLE_BACKGROUND     940
#define GFX_MINI_GAME_FRAME_L5          941
#define GFX_MINI_GAME_FRAME_L1          942
#define GFX_MINI_GAME_FRAME_L2          943
#define GFX_MINI_GAME_FRAME_L3          944
#define GFX_MINI_GAME_FRAME_L4          945
#define GFX_MINI_GAME_FRAME_R5          946
#define GFX_MINI_GAME_FRAME_R1          947
#define GFX_MINI_GAME_FRAME_R2          948
#define GFX_MINI_GAME_FRAME_R3          949
#define GFX_MINI_GAME_FRAME_R4          950
#define GFX_ENGINEER_NUCLEUS_8          951
#define GFX_ENGINEER_NUCLEUS_1          952
#define GFX_ENGINEER_NUCLEUS_2          953
#define GFX_ENGINEER_NUCLEUS_3          954
#define GFX_ENGINEER_NUCLEUS_4          955
#define GFX_ENGINEER_NUCLEUS_5          956
#define GFX_ENGINEER_NUCLEUS_6          957
#define GFX_ENGINEER_NUCLEUS_7          958
#define SFX_WALKING                     959
#define GFX_THE_ESCAPE_PLAYER_DOWN      964
#define GFX_THE_ESCAPE_PLAYER_LEFT      965
#define GFX_THE_ESCAPE_PLAYER_RIGHT     966
#define GFX_THE_ESCAPE_PLAYER_UP        967
#define GFX_THE_ESCAPE_WALL_2           968
#define SFX_ENGINEER_PARTICLE_GOOD      977
#define SFX_ALIEN_BABBLE_BABBLING       978
#define SFX_ALIEN_BABBLE_HIT            979
#define SFX_ENGINEER_DIVERTER           981
#define SFX_ENGINEER_PARTICLE_BAD       982
#define SFX_ENGINEER_PARTICLE_EMERGING  983
#define SFX_THE_REDEYE_ORDER_WIN        984
#define SFX_FAR_OUT_FOWL_CATCH          985
#define SFX_FAR_OUT_FOWL_CHICKEN        986
#define SFX_FFOPIR_SIRTET_PAEHC_LANDED_CLEARED 987
#define SFX_FFOPIR_SIRTET_PAEHC_ROTATING 988
#define SFX_LEPAR_LAND_MOANING          989
#define SFX_THE_REDEYE_ORDER_MOVE       990
#define SFX_COSMIC_SQUIRREL_WALKING     991
#define SFX_THE_ESCAPE_LEVELUP          992
#define SFX_THE_ESCAPE_PUSH             993
#define SFX_MUNCHER_DUDE_ALIENS         995
#define SFX_MUNCHER_DUDE_BITE           996
#define SFX_SQUISHEM_SWITCH_GROUPS      997
#define SFX_SQUISHEM_ALIEN_POPUP        998
#define SFX_SQUISHEM_LASER              999
#define SFX_SQUISHEM_SQUISH             1000
#define GFX_FINAL_SCORE_BACKGROUND      1001
#define SFX_HEARTBEAT_1                 1002
#define SFX_HEARTBEAT_2                 1003
#define GFX_HENRY_DEAD_3                1004
#define GFX_HENRY_DEAD_1                1005
#define GFX_HENRY_DEAD_2                1006
#define SFX_VOICE_GENTOO_20             1007
#define GFX_GENTOO_08                   1008
#define GFX_GENTOO_07                   1009
#define GFX_GENTOO_09                   1010
#define GFX_KRELMAC_09                  1011
#define GFX_KRELMAC_07                  1012
#define GFX_KRELMAC_08                  1013
#define GFX_KRELMAC_11                  1014
#define GFX_KRELMAC_10                  1015
#define SFX_BOGAZ_HONK                  1016
#define SFX_BOGAZ_CRASH                 1017
#define SFX_BOGAZ_CAR                   1018
#define GFX_HENRY_BEAMINGUP_1           1019
#define GFX_HENRY_BEAMINGUP_2           1020
#define GFX_HENRY_BEAMINGUP_3           1021
#define GFX_HENRY_BEAMINGUP_4           1022
#define GFX_HENRY_BEAMINGUP_5           1023
#define GFX_HENRY_WANDERING_6           1024
#define GFX_HENRY_WANDERING_1           1025
#define GFX_HENRY_WANDERING_2           1026
#define GFX_HENRY_WANDERING_3           1027
#define GFX_HENRY_WANDERING_4           1028
#define GFX_HENRY_WANDERING_5           1029
#define GFX_VIEWSCREEN_STATIC_3         1030
#define GFX_VIEWSCREEN_STATIC_1         1031
#define GFX_VIEWSCREEN_STATIC_2         1032
#define GFX_HENRY_CAPTIVE_4             1033
#define GFX_HENRY_CAPTIVE_1             1034
#define GFX_HENRY_CAPTIVE_2             1035
#define GFX_HENRY_CAPTIVE_3             1036
#define SFX_AAAH                        1037
#define SFX_MUSIC_SULLY                 1038
#define SFX_MUSIC_BRENDA                1039
#define SFX_MUSIC_CATRINA               1040
#define SFX_MUSIC_EEGER                 1041
#define SFX_MUSIC_FRED                  1042
#define GFX_HENRY_JUMPING_1             1046
#define GFX_HENRY_JUMPING_2             1047
#define SFX_MUSIC_WON                   1048
#define GFX_HAPPY_BURST                 1049
#define GFX_TILE_CONSOLE_01             1050
#define GFX_POCKETGAMER                 1057
#define GFX_MENU_HIGH_SCORES_1          1058
#define GFX_MENU_HIGH_SCORES_0          1059
#define GFX_LOGO_CLICKGAMER             1061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1062
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
