//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by InvasionTrivia.rc
//
#define IDS_BRELNAR_MEANWHILE           30
#define IDR_UFO_002                     135
#define IDR_UFO_003                     136
#define IDR_UFO_004                     137
#define IDR_UFO_001                     138
#define IDR_EXPLOSION_002               140
#define IDR_EXPLOSION_003               141
#define IDR_EXPLOSION_004               142
#define IDR_EXPLOSION_005               143
#define IDR_EXPLOSION_001               146
#define IDR_LASER_003                   147
#define IDR_LASER_002                   148
#define IDR_LASER_001                   149
#define IDR_SFX_UFO_HUM                 152
#define IDR_SFX_LASER                   153
#define IDR_SFX_EXPLOSION               154
#define IDR_PVLOGO                      160
#define IDR_OTXLOGO                     161
#define IDR_TITLE_SCENE_BACKGROUND      165
#define IDR_TITLE_SCENE_SCRIPT          165
#define IDR_INVASIONTRIVIA_TITLE        167
#define IDR_START_GAME_INTRO_1_SCENE_SCRIPT 168
#define IDR_CORRECT_ANSWER_1_SCENE_SCRIPT 187
#define IDR_WORLD_DESTRUCTION_1_SCENE_SCRIPT 188
#define IDR_PLAYER_WINS_1_SCENE_SCRIPT  189
#define IDI_ICON                        192
#define IDR_MAIN_MENU_CREDITS_0         202
#define IDR_MAIN_MENU_CREDITS_1         203
#define IDR_MAIN_MENU_EXIT_0            204
#define IDR_MAIN_MENU_EXIT_1            205
#define IDR_MAIN_MENU_HIGH_SCORES_0     206
#define IDR_MAIN_MENU_HIGH_SCORES_1     207
#define IDR_MAIN_MENU_INSTRUCTIONS_0    208
#define IDR_MAIN_MENU_INSTRUCTIONS_1    209
#define IDR_MAIN_MENU_SETTINGS_0        210
#define IDR_MAIN_MENU_SETTINGS_1        211
#define IDR_MAIN_MENU_START_GAME_0      212
#define IDR_MAIN_MENU_START_GAME_1      213
#define IDR_MAIN_MENU_SHOCK_1           214
#define IDR_MAIN_MENU_SHOCK_2           215
#define IDR_MAIN_MENU_SHOCK_3           216
#define IDR_MAIN_MENU_SHOCK_4           217
#define IDR_MAIN_MENU_SHOCK_5           218
#define IDR_MAIN_MENU_SHOCK_6           219
#define IDR_SFX_TICK                    220
#define IDR_SFX_TOCK                    221
#define IDR_CORRECT_ANSWER_5_SCENE_SCRIPT 234
#define IDR_CORRECT_ANSWER_3_SCENE_SCRIPT 235
#define IDR_CORRECT_ANSWER_4_SCENE_SCRIPT 236
#define IDR_CORRECT_ANSWER_2_SCENE_SCRIPT 237
#define IDR_PLAYER_WINS_5_SCENE_SCRIPT  238
#define IDR_PLAYER_WINS_3_SCENE_SCRIPT  239
#define IDR_PLAYER_WINS_4_SCENE_SCRIPT  240
#define IDR_PLAYER_WINS_2_SCENE_SCRIPT  241
#define IDR_START_GAME_INTRO_5_SCENE_SCRIPT 242
#define IDR_START_GAME_INTRO_3_SCENE_SCRIPT 243
#define IDR_START_GAME_INTRO_4_SCENE_SCRIPT 244
#define IDR_START_GAME_INTRO_2_SCENE_SCRIPT 245
#define IDR_WORLD_DESTRUCTION_5_SCENE_SCRIPT 246
#define IDR_WORLD_DESTRUCTION_3_SCENE_SCRIPT 247
#define IDR_WORLD_DESTRUCTION_4_SCENE_SCRIPT 248
#define IDR_WORLD_DESTRUCTION_2_SCENE_SCRIPT 249
#define IDR_MATTER_ANTIMATTER_0         253
#define IDR_ASK_THE_ANDROMEDANS_0       254
#define IDR_BEAM_A_BRELNAR_0            255
#define IDR_MATTER_ANTIMATTER_1         256
#define IDR_ASK_THE_ANDROMEDANS_1       257
#define IDR_BEAM_A_BRELNAR_1            258
#define IDR_MATTER_ANTIMATTER_SCENE_SCRIPT 260
#define IDR_ASK_THE_ANDROMEDANS_SCENE_SCRIPT 261
#define IDR_BEAM_A_BRELNAR_SCENE_SCRIPT 262
#define IDR_ANSWER_SCREEN_BACKGROUND    264
#define IDR_MATTER_ANTIMATTER_DISABLED  266
#define IDR_ASK_THE_ANDROMEDANS_DISABLED 267
#define IDR_BEAM_A_BRELNAR_DISABLED     268
#define IDR_BOOK_OF_KNOWLEDGE_DISABLED  269
#define IDR_BOOK_OF_KNOWLEDGE_0         270
#define IDR_BOOK_OF_KNOWLEDGE_1         271
#define IDR_BOOK_OF_KNOWLEDGE_SCENE_SCRIPT 272
#define IDR_POINT_LEVELS_SCREEN_BACKGROUND 273
#define IDR_PFE_POPUP_YES_0             279
#define IDR_PFE_POPUP_NO_0              280
#define IDR_PFE_POPUP_YES_1             281
#define IDR_PFE_POPUP_NO_1              282
#define IDR_ABANDON_GAME_BUTTON_0       283
#define IDR_ABANDON_GAME_BUTTON_1       284
#define IDR_NEXT_QUESTION_BUTTON_0      285
#define IDR_NEXT_QUESTION_BUTTON_1      286
#define IDR_ANSWER_BOX                  287
#define IDR_FONT_DEFAULT                288
#define IDR_FONT_20S                    289
#define IDR_FONT_ANTIQUE                290
#define IDR_FONT_ART                    291
#define IDR_FONT_BOLD                   292
#define IDR_FONT_BOXROUND               293
#define IDR_FONT_CP112                  294
#define IDR_FONT_KANA                   295
#define IDR_FONT_MERP                   296
#define IDR_FONT_MODERN                 297
#define IDR_FONT_POOTER                 298
#define IDR_PFE_DROPDOWN_0              299
#define IDR_PFE_DROPDOWN_ARROWDIVIDER   303
#define IDR_PFE_DROPDOWN_DOWNARROW_0    304
#define IDR_PFE_DROPDOWN_UPARROW_0      305
#define IDR_PFE_DROPDOWN_DROPBOX_LINETWO 306
#define IDR_PFE_DROPDOWN_DROPBOX        307
#define IDR_PFE_DROPDOWN_DROPBOX_LINEONE 308
#define IDR_PFE_DROPDOWN_DROPBOX_LINETHREE 309
#define IDR_PFE_DROPDOWN_UPARROW_1      310
#define IDR_PFE_DROPDOWN_1              311
#define IDR_PFE_DROPDOWN_DOWNARROW_1    312
#define IDR_QAC                         313
#define IDR_PFE_POPUP_BORDER            314
#define IDR_ANSWER_BAB_ATA_BOX          315
#define IDR_VIEWSCREEN                  316
#define IDR_ICON_TRAY_SLIDE_OUT_1       317
#define IDR_ICON_TRAY_SLIDE_IN_0        318
#define IDR_ICON_TRAY_SLIDE_IN_1        319
#define IDR_ICON_TRAY_SLIDE_OUT_0       320
#define IDR_SFX_STYLUSSOUND             327
#define IDR_SFX_RETURN_TO_MENU          328
#define IDR_SFX_DROPDOWN_BUTTONS        329
#define IDR_SFX_DROPDOWN_DROPPED        330
#define IDR_SFX_DROPDOWN_ITEM_SELECTED  331
#define IDR_CREDITS_LINE                332
#define IDR_SFX_POPUP_NO                333
#define IDR_SFX_POPUP_YES               334
#define IDR_SFX_ICON_SLIDE              335
#define IDR_CHARACTER_SELECT_SCREEN_BACKGROUND 337
#define IDR_CHARACTER_SELECT_BOX        338
#define IDR_SFX_CHARACTER_SELECT        339
#define IDR_SFX_DRUMROLL                340
#define IDR_INS_PREV_1                  343
#define IDR_INS_NEXT_0                  344
#define IDR_INS_NEXT_1                  345
#define IDR_INS_PREV_0                  346
#define IDR_GENTOO_BODY_WHACKOFF        351
#define IDR_GENTOO_BODY                 352
#define IDR_GENTOO_HEAD_EMBARASSED_BLUSHING 353
#define IDR_GENTOO_HEAD_EMBARASSED      354
#define IDR_GENTOO_HEAD_LOOKING_DOWN    355
#define IDR_GENTOO_HEAD_MOUTH_CLOSED    356
#define IDR_GENTOO_HEAD_MOUTH_OPENED    357
#define IDR_GENTOO_HEAD_MOUTH_OPENED_WIDE 358
#define IDR_SHIP_INTERIOR               359
#define IDR_KRELMAC_HEAD_MOUTH_OPENED   360
#define IDR_KRELMAC_BODY                361
#define IDR_KRELMAC_HEAD_MOUTH_CLOSED   362
#define IDR_KRELMAC_HEAD_MOUTH_OPENED_WIDE 363
#define IDR_KRELMAC_EYEBROWS            364
#define IDR_VIEWSCREEN_GENTOO           365
#define IDR_VIEWSCREEN_KRELMAC          366
#define IDR_VIEWSCREEN_KRELMAC_AND_GENTOO 367
#define IDR_SFX_K_WWYAGOR               374
#define IDR_SFX_G_ILHANIBWYI            375
#define IDR_SFX_INSTRUCTIONS_ARROWS     376
#define IDR_CONGRATSBGROUND             377
#define IDR_SFX_K_DWMLYSIWL             378
#define IDR_SFX_G_IDBIKTNO              379
#define IDR_SFX_K_NMTTMTNOFS            380
#define IDR_SFX_G_YSHLMPITQAQT          381
#define IDR_SFX_K_ITTMTOFSG             382
#define IDR_DESTRUCTION_PARIS_SCENE_SCRIPT 383
#define IDR_DESTRUCTION_GIZA_SCENE_SCRIPT 384
#define IDR_DESTRUCTION_LONDON_SCENE_SCRIPT 385
#define IDR_DESTRUCTION_MOSCOW_SCENE_SCRIPT 386
#define IDR_DESTRUCTION_TOKYO_SCENE_SCRIPT 387
#define IDR_DESTRUCTION_PISA_SCENE_SCRIPT 388
#define IDR_DESTRUCTION_ROME_SCENE_SCRIPT 389
#define IDR_DESTRUCTION_ST_LOUIS_SCENE_SCRIPT 390
#define IDR_LIVECITY_PARIS              392
#define IDR_DEADCITY_PARIS              393
#define IDR_SFX_K_LSYDTA                394
#define IDR_SFX_G_YYGGRBG               395
#define IDR_SFX_K_HCYPKTYMHGH           396
#define IDR_SFX_BOUNCE_SOUND            400
#define IDR_DEADCITY_GIZA               409
#define IDR_DEADCITY_LONDON             410
#define IDR_DEADCITY_MOSCOW             411
#define IDR_DEADCITY_TOKYO              412
#define IDR_DEADCITY_ROME               413
#define IDR_DEADCITY_ST_LOUIS           414
#define IDR_LIVECITY_MOSCOW             415
#define IDR_LIVECITY_GIZA               417
#define IDR_LIVECITY_LONDON             418
#define IDR_LIVECITY_TOKYO              419
#define IDR_LIVECITY_ROME               420
#define IDR_LIVECITY_ST_LOUIS           421
#define IDR_THEME_MUSIC                 422
#define IDR_SFX_DESTRUCTION_WORDS_TOKYO 423
#define IDR_SFX_DESTRUCTION_WORDS_MOSCOW 424
#define IDR_SFX_DESTRUCTION_WORDS_ST_LOUIS 425
#define IDR_SFX_DESTRUCTION_WORDS_ROME  426
#define IDR_SFX_DESTRUCTION_WORDS_LONDON 427
#define IDR_SFX_DESTRUCTION_WORDS_GIZA  428
#define IDR_SFX_CONGRATS_SOUND          430
#define IDR_SFX_CONGRATS_DONE           431
#define IDR_SFX_CONGRATS_BACKSPACE      432
#define IDR_CHARACTER_MALE_2_D          433
#define IDR_CHARACTER_MALE_1_A          434
#define IDR_CHARACTER_MALE_1_B          435
#define IDR_CHARACTER_MALE_1_C          436
#define IDR_CHARACTER_MALE_1_D          437
#define IDR_CHARACTER_MALE_2_A          438
#define IDR_CHARACTER_MALE_2_B          439
#define IDR_CHARACTER_MALE_2_C          440
#define IDR_CHARACTER_FEMALE_2_D        441
#define IDR_CHARACTER_FEMALE_1_A        442
#define IDR_CHARACTER_FEMALE_1_B        443
#define IDR_CHARACTER_FEMALE_1_C        444
#define IDR_CHARACTER_FEMALE_1_D        445
#define IDR_CHARACTER_FEMALE_2_A        446
#define IDR_CHARACTER_FEMALE_2_B        447
#define IDR_CHARACTER_FEMALE_2_C        448
#define IDR_CHARACTER_FEMALE_3_D        449
#define IDR_CHARACTER_FEMALE_3_A        450
#define IDR_CHARACTER_FEMALE_3_B        451
#define IDR_CHARACTER_FEMALE_3_C        452
#define IDR_CHARACTER_MALE_3_D          453
#define IDR_CHARACTER_MALE_3_A          454
#define IDR_CHARACTER_MALE_3_B          455
#define IDR_CHARACTER_MALE_3_C          456
#define IDR_LIVECITY_PISA               457
#define IDR_DEADCITY_PISA               458
#define IDR_SFX_DESTRUCTION_WORDS_PISA  459
#define IDR_SFX_K_YILTSOBHFITN          460
#define IDR_SFX_G_IWUTECKTIGBF          461
#define IDR_SFX_K_ATTGTSOTR             462
#define IDR_SFX_K_G                     463
#define IDR_SFX_G_BIWTSI                464
#define IDR_SFX_G_S                     465
#define IDR_SFX_G_WTAEOSYWPH            466
#define IDR_SFX_K_GTWML                 467
#define IDR_SFX_BRELNAR_CRICKET         468
#define IDR_SFX_BRELNAR_BEAM_SOUND      469
#define IDR_BRELNAR_SHOCKED_RIGHT       470
#define IDR_BRELNAR_BEAM_1              471
#define IDR_BRELNAR_BEAM_2              472
#define IDR_BRELNAR_BEAM_COMING_DOWN    473
#define IDR_BRELNAR_BEAM_UP_1           474
#define IDR_BRELNAR_BEAM_UP_2           475
#define IDR_BRELNAR_BORED               476
#define IDR_BRELNAR_SHOCKED_LEFT        477
#define IDR_BRELNAR_BACKGROUND          478
#define IDR_SFX_ANSWER_DONE             479
#define IDR_SFX_K_GTGTP                 480
#define IDR_SFX_G_YYLITHUYWTSAMOTA      481
#define IDR_SFX_K_WNYCHRYPBST           482
#define IDR_SFX_K_YKTRGTHTGAQWF         483
#define IDR_SFX_G_WWAWWFIWBS            484
#define IDR_SFX_K_DWGTODLTBIWBL         485
#define IDR_SFX_G_HKCIFTECYHHCIH        486
#define IDR_BRELNAR_WHAT_THE            487
#define IDR_BRELNAR_BRIGHT_IDEA         488
#define IDR_BRELNAR_LATER_JOE           489
#define IDR_BRELNAR_QUIZZICAL           490
#define IDR_BRELNAR_WORDS_THANKYOUNOWGETOUT 491
#define IDR_BRELNAR_WORDS_CHOOSEANANSWER 492
#define IDR_BRELNAR_WORDS_PITIFULBRELNAR 493
#define IDR_BOK_BACKGROUND              494
#define IDR_BOK_1                       495
#define IDR_BOK_2                       496
#define IDR_BOK_3                       497
#define IDR_BOK_4                       498
#define IDR_BOK_5                       499
#define IDR_SFX_HARP                    500
#define IDR_SFX_K_YDHABG                501
#define IDR_SFX_K_PHYDIIMT              502
#define IDR_SFX_G_NWKTDIIMB             503
#define IDR_SFX_G_EEWW                  504
#define IDR_SFX_G_TWTASCF               505
#define IDR_SFX_K_IMBTH                 506
#define IDR_SFX_ASKTHEANDROMEDANS       507
#define IDR_ASKTHEANDROMEDANS           508
#define IDR_SFX_K_NII                   509
#define IDR_SFX_K_TNWYCDTAT             510
#define IDR_SFX_G_YNWNWNWNW             511
#define IDR_SFX_K_FWBOOWN               512
#define IDR_SFX_G_UNTA                  513
#define IDR_SFX_G_WNTCHWNWK             514
#define IDR_SFX_K_ISHISS                515
#define IDR_SFX_G_SSK                   516
#define IDR_SFX_K_IGITFUTLG             517
#define IDR_SFX_G_BIDWGIWBSUK           518
#define IDR_SFX_K_IKGIKIASDFUHIB        523
#define IDR_SFX_G_NKIKLTP               524
#define IDR_SFX_K_TSSITYSSS             525
#define IDR_SFX_K_YWYWIDKHBYW           526
#define IDR_SFX_G_KTHGIRTGIRK           527
#define IDR_SFX_G_YYSDHIBYY             528
#define IDR_SFX_G_TSKSWTICSWT           529
#define IDR_SFX_G_TCTMHNHCHW            530
#define IDR_SFX_K_WSTGAFCATGO           531
#define IDR_SFX_K_IIDGRATTWWNT          532
#define IDR_SFX_GAMEEXITSOUND           533
#define IDR_SFX_K_FWLBWBBSD             534
#define IDR_SFX_G_IMK                   535
#define IDR_SFX_K_YHDU                  536
#define IDR_SFX_K_UTHEYEIWLF            537
#define IDR_SFX_G_TPWCABA               538
#define IDR_SFX_G_DTRTTWK               539
#define IDR_SFX_G_N                     540
#define IDR_SFX_G_WTK                   541
#define IDR_SFX_G_YBYWSAWYAWTV          542
#define IDR_SFX_K_FTPPALGOH             543
#define IDR_SFX_K_IALTBD                544
#define IDR_SFX_K_VW                    545
#define IDR_SFX_K_WGIGTDKOASA           546
#define IDR_SFX_K_WWT                   547
#define IDR_DESTRUCTION_EARTH           548
#define IDR_DESTRUCTION_EARTH_DESTROYED 549
#define IDR_DESTRUCTION_UFO_ZOOM_01     550
#define IDR_DESTRUCTION_UFO_ZOOM_02     551
#define IDR_DESTRUCTION_UFO_ZOOM_03     552
#define IDR_DESTRUCTION_UFO_ZOOM_04     553
#define IDR_DESTRUCTION_UFO_ZOOM_05     554
#define IDR_DESTRUCTION_UFO_ZOOM_06     555
#define IDR_DESTRUCTION_UFO_ZOOM_07     556
#define IDR_DESTRUCTION_UFO_ZOOM_08     557
#define IDR_DESTRUCTION_UFO_ZOOM_09     558
#define IDR_DESTRUCTION_UFO_ZOOM_10     559
#define IDR_DESTRUCTION_UFO_ZOOM_11     560
#define IDR_DESTRUCTION_UFO_ZOOM_12     561
#define IDR_DESTRUCTION_UFO_ZOOM_13     562
#define IDR_DESTRUCTION_UFO_ZOOM_14     563
#define IDR_DESTRUCTION_UFO_ZOOM_15     564
#define IDR_SFX_K_GPGITCTHNIOTPOTDS     565
#define IDR_SFX_K_HMTHITYGDMWL          566
#define IDR_SFX_G_BWATBLUK              567
#define IDR_SFX_G_IFAGDITF              568
#define IDR_SFX_G_WGRFAWLSK             569
#define IDR_SFX_G_WIDTPIMWK             570
#define IDR_SFX_G_WTYVMK                571
#define IDR_SFX_K_GSITYEDPALTM          572
#define IDR_SFX_K_OISG                  573
#define IDR_SFX_K_YQWGNF                574
#define IDR_SFX_G_IDGI                  576
#define IDR_SFX_G_SWK                   577
#define IDR_SFX_G_U                     578
#define IDR_SFX_G_YBIHTDB               579
#define IDR_SFX_K_AF                    580
#define IDR_SFX_K_GIHTEWCOAS            581
#define IDR_SFX_K_GYASAT                582
#define IDR_SFX_K_TADTL                 583
#define IDR_SFX_G_SWIIAMAANATFEWAIAV    584
#define IDR_SFX_G_YMTK                  585
#define IDR_SFX_G_YNSACFAK              586
#define IDR_SFX_K_AYCG                  587
#define IDR_SFX_K_IGMTPBMG              588
#define IDR_SFX_K_RBIWJA                589
#define IDR_SFX_K_YCR                   590
#define IDR_KGSHIP_FULLSCREEN           591
#define IDR_HS_NONE                     592
#define IDR_ANTIATOM_01                 593
#define IDR_ANTIATOM_02                 594
#define IDR_ANTIATOM_03                 595
#define IDR_ANTIATOM_04                 596
#define IDR_ANTIATOM_05                 597
#define IDR_ANTIATOM_06                 598
#define IDR_ANTIATOM_07                 599
#define IDR_ANTIATOM_08                 600
#define IDR_ANTIATOM_09                 601
#define IDR_ANTIATOM_10                 602
#define IDR_ANTIATOM_11                 603
#define IDR_ANTIATOM_12                 604
#define IDR_ATOM_01                     605
#define IDR_ATOM_02                     606
#define IDR_ATOM_03                     607
#define IDR_ATOM_04                     608
#define IDR_ATOM_05                     609
#define IDR_ATOM_06                     610
#define IDR_ATOM_07                     611
#define IDR_ATOM_08                     612
#define IDR_ATOM_09                     613
#define IDR_ATOM_10                     614
#define IDR_ATOM_11                     615
#define IDR_ATOM_12                     616
#define IDR_SFX_DESTRUCTION_WORDS_PARIS 623
#define IDR_SFX_G_BUHAHAHA              624
#define IDR_SFX_G_HNACD                 625
#define IDR_SFX_G_T                     626
#define IDR_SFX_K_BUHAHAHA              627
#define IDR_SFX_K_F                     628
#define IDR_SFX_K_OJ                    629
#define IDR_SFX_G_KCIFTECYHHCI          632
#define IDR_KANDG_LAUGHING              633
#define IDR_CLICKGAMER                  634

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        635
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
