
	typedef struct tagCOPPERWIRE {
		  TCHAR szAWG[10];
			TCHAR szNominalBareDiameterInches[10];
			TCHAR szNominalCircularMils[10];
			TCHAR szNominalFeetPerPoundBare[10];
			TCHAR szNominalOhmsPerThousandFeet[10];
		  TCHAR szCurrentCarryingCapacity[10];
		  TCHAR szTurnsPerLinearInchSingleFilmCoated[10];
		  TCHAR szTurnsPerLinearInchHeavyFilmCoated[10];
	}		COPPERWIRE;

	typedef struct tagCOPPERWIRECOLS	{
		  TCHAR szText[32];
			int intSize;
	} COPPERWIRECOLS;

  COPPERWIRECOLS CopperWireColsTable[] = {
    {TEXT("AWG"),												50}, 
    {TEXT("Nom Bare Diam"),							100}, 
    {TEXT("Nom Circ Mils"),							100},
    {TEXT("Nom Bare Ft/Lbs"),						120},
    {TEXT("Nom Ohms/1000 Ft@20C"),			160},   
    {TEXT("Curr Carrying Cap@700CM/A"), 170},
    {TEXT("Turns/Lin In S Film Coat"),  160},  
    {TEXT("Turns/Lin In H Film Coat"),  160}, 
  };

	int numItemsCopperWire = 64;

  COPPERWIRE CopperWireTable[] = {
		{TEXT("0000"),TEXT("0.46"), 		TEXT("211600"), TEXT("1.561"), 	TEXT("0.04901"),TEXT("302.3"), 	TEXT("-"), 		TEXT("-")}, 																																																																																																																																																																																																																																																							
		{TEXT("000"), TEXT("0.4096"), 	TEXT("167800"), TEXT("1.969"), 	TEXT("0.06182"),TEXT("239.7"), 	TEXT("-"), 		TEXT("-")}, 																																																																																																																																																																																																																																																							
		{TEXT("00"), 	TEXT("0.3648"), 	TEXT("133100"), TEXT("2.482"), 	TEXT("0.07793"),TEXT("190.1"), 	TEXT("-"), 		TEXT("-")}, 																																																																																																																																																																																																																																																							
		{TEXT("0"), 	TEXT("0.3249"), 	TEXT("105600"), TEXT("3.13"), 	TEXT("0.09825"),TEXT("150.9"), 	TEXT("-"), 		TEXT("-")}, 																																																																																																																																																																																																																																																							
		{TEXT("1"), 	TEXT("0.2893"), 	TEXT("83690"), 	TEXT("3.947"), 	TEXT("0.1239"), TEXT("119.6"), 	TEXT("-"), 		TEXT("-")}, 																																																																																																																																																																																																																																																							
		{TEXT("2"), 	TEXT("0.2576"), 	TEXT("66360"), 	TEXT("4.978"), 	TEXT("0.1563"), TEXT("94.8"), 	TEXT("-"), 		TEXT("-")}, 																																																																																																																																																																																																																																																							
		{TEXT("3"), 	TEXT("0.2294"), 	TEXT("52620"), 	TEXT("6.278"), 	TEXT("0.1971"), TEXT("75.2"), 	TEXT("-"), 		TEXT("-")}, 																																																																																																																																																																																																																																																							
		{TEXT("4"), 	TEXT("0.2043"), 	TEXT("41740"), 	TEXT("7.915"), 	TEXT("0.2485"), TEXT("59.6"), 	TEXT("-"), 		TEXT("4.8")}, 																																																																																																																																																																																																																																																							
		{TEXT("5"), 	TEXT("0.1819"), 	TEXT("33090"), 	TEXT("9.984"), 	TEXT("0.3134"), TEXT("47.3"), 	TEXT("-"), 		TEXT("5.38")}, 																																																																																																																																																																																																																																																							
		{TEXT("6"), 	TEXT("0.162"), 		TEXT("26240"), 	TEXT("12.59"), 	TEXT("0.3952"), TEXT("37.5"), 	TEXT("-"), 		TEXT("6.03")}, 																																																																																																																																																																																																																																																							
		{TEXT("7"), 	TEXT("0.1443"), 	TEXT("20820"), 	TEXT("15.87"), 	TEXT("0.4981"), TEXT("29.7"), 	TEXT("-"), 		TEXT("6.75")}, 																																																																																																																																																																																																																																																							
		{TEXT("8"), 	TEXT("0.1285"), 	TEXT("16510"), 	TEXT("20.01"), 	TEXT("0.6281"), TEXT("23.6"), 	TEXT("-"), 		TEXT("7.57")}, 																																																																																																																																																																																																																																																							
		{TEXT("9"), 	TEXT("0.1144"), 	TEXT("13090"), 	TEXT("25.24"), 	TEXT("0.7925"), TEXT("18.7"), 	TEXT("-"), 		TEXT("8.48")}, 																																																																																																																																																																																																																																																							
		{TEXT("l0"), 	TEXT("0.1019"), 	TEXT("10380"), 	TEXT("31.82"), 	TEXT("0.9988"), TEXT("14.8"), 	TEXT("-"), 		TEXT("9.5")}, 																																																																																																																																																																																																																																																							
		{TEXT("I1"), 	TEXT("0.0907"), 	TEXT("8230"), 	TEXT("40.2"), 	TEXT("1.26"), 	TEXT("11.8"), 	TEXT("-"), 		TEXT("10.6")}, 																																																																																																																																																																																																																																																							
		{TEXT("2"), 	TEXT("0.0808"), 	TEXT("6530"), 	TEXT("50.6"), 	TEXT("1.59"), 	TEXT("9.33"), 	TEXT("-"), 		TEXT("11.9")}, 																																																																																																																																																																																																																																																							
		{TEXT("3"), 	TEXT("0.072"), 		TEXT("5180"), 	TEXT("63.7"), 	TEXT("2"), 			TEXT("7.4"), 		TEXT("-"), 		TEXT("13.3")}, 																																																																																																																																																																																																																																																							
		{TEXT("4"), 	TEXT("0.0641"), 	TEXT("4110"), 	TEXT("80.4"), 	TEXT("2.52"), 	TEXT("5.87"), 	TEXT("15.2"), TEXT("14.8")}, 																																																																																																																																																																																																																																																							
		{TEXT("5"), 	TEXT("0.0571"), 	TEXT("3260"), 	TEXT("101"), 		TEXT("3.18"), 	TEXT("4.66"), 	TEXT("17"), 	TEXT("16.6")}, 																																																																																																																																																																																																																																																							
		{TEXT("6"), 	TEXT("0.0508"), 	TEXT("2580"), 	TEXT("128"), 		TEXT("4.02"), 	TEXT("3.69"), 	TEXT("19"), 	TEXT("18.5")}, 																																																																																																																																																																																																																																																							
		{TEXT("7"), 	TEXT("0.0453"), 	TEXT("2050"), 	TEXT("161"), 		TEXT("5.05"), 	TEXT("2.93"), 	TEXT("21.3"), TEXT("20.7")}, 																																																																																																																																																																																																																																																							
		{TEXT("18"), 	TEXT("0.0403"), 	TEXT("1620"), 	TEXT("203"), 		TEXT("6.39"), 	TEXT("2.31"), 	TEXT("23.9"), TEXT("23.1")}, 																																																																																																																																																																																																																																																							
		{TEXT("19"), 	TEXT("0.0359"), 	TEXT("1290"), 	TEXT("256"), 		TEXT("8.05"), 	TEXT("1.84"), 	TEXT("26.7"), TEXT("25.9")}, 																																																																																																																																																																																																																																																							
		{TEXT("20"), 	TEXT("0.032"), 		TEXT("1020"), 	TEXT("323"), 		TEXT("10.1"), 	TEXT("1.46"), 	TEXT("29.9"), TEXT("28.9")}, 																																																																																																																																																																																																																																																							
		{TEXT("21"), 	TEXT("0.0285"), 	TEXT("812"), 		TEXT("407"), 		TEXT("12.8"), 	TEXT("1.16"), 	TEXT("33.4"), TEXT("32.3")}, 																																																																																																																																																																																																																																																							
		{TEXT("22"), 	TEXT("0.0253"), 	TEXT("640"), 		TEXT("516"), 		TEXT("16.2"), 	TEXT("0.914"), 	TEXT("37.5"), TEXT("36.1")}, 																																																																																																																																																																																																																																																							
		{TEXT("23"), 	TEXT("0.0226"), 	TEXT("511"), 		TEXT("647"), 		TEXT("20.3"), 	TEXT("0.73"), 	TEXT("41.8"), TEXT("40.2")}, 																																																																																																																																																																																																																																																							
		{TEXT("24"), 	TEXT("0.0201"), 	TEXT("404"), 		TEXT("818"), 		TEXT("25.7"), 	TEXT("0.577"), 	TEXT("46.8"), TEXT("44.8")}, 																																																																																																																																																																																																																																																							
		{TEXT("25"), 	TEXT("0.0179"), 	TEXT("320"), 		TEXT("1030"), 	TEXT("32.4"), 	TEXT("0.457"), 	TEXT("52.5"), TEXT("50.1")}, 																																																																																																																																																																																																																																																							
		{TEXT("26"), 	TEXT("0.0159"), 	TEXT("253"), 		TEXT("1310"), 	TEXT("41"), 		TEXT("0.361"), 	TEXT("58.8"), TEXT("56")}, 																																																																																																																																																																																																																																																							
		{TEXT("27"), 	TEXT("0.0142"), 	TEXT("202"), 		TEXT("1640"), 	TEXT("51.4"), 	TEXT("0.289"), 	TEXT("65.6"), TEXT("62.3")}, 																																																																																																																																																																																																																																																							
		{TEXT("28"), 	TEXT("0.0126"), 	TEXT("159"), 		TEXT("2080"), 	TEXT("65.3"), 	TEXT("0.227"), 	TEXT("73.3"), TEXT("69.4")}, 																																																																																																																																																																																																																																																							
		{TEXT("29"), 	TEXT("0.0113"), 	TEXT("123"), 		TEXT("2590"), 	TEXT("81.2"), 	TEXT("0.183"), 	TEXT("81.6"), TEXT("76.9")}, 																																																																																																																																																																																																																																																							
		{TEXT("30"), 	TEXT("0.01"), 		TEXT("100"), 		TEXT("3300"), 	TEXT("104"), 		TEXT("0.143"), 	TEXT("91.7"), TEXT("86.2")}, 																																																																																																																																																																																																																																																							
		{TEXT("31"), 	TEXT("0.0089"), 	TEXT("79.2"), 	TEXT("4170"), 	TEXT("131"), 		TEXT("0.113"), 	TEXT("103"), 	TEXT("96")}, 																																																																																																																																																																																																																																																							
		{TEXT("32"), 	TEXT("0.008"), 		TEXT("64"), 		TEXT("5160"), 	TEXT("162"), 		TEXT("0.091"), 	TEXT("114"), 	TEXT("106")}, 																																																																																																																																																																																																																																																							
		{TEXT("33"), 	TEXT("0.0071"), 	TEXT("50.4"), 	TEXT("6550"), 	TEXT("206"), 		TEXT("0.072"), 	TEXT("128"), 	TEXT("118")}, 																																																																																																																																																																																																																																																							
		{TEXT("34"), 	TEXT("0.0063"), 	TEXT("39.7"), 	TEXT("8320"), 	TEXT("261"), 		TEXT("0.057"), 	TEXT("145"), 	TEXT("133")}, 																																																																																																																																																																																																																																																							
		{TEXT("35"), 	TEXT("0.0056"), 	TEXT("31.4"), 	TEXT("10500"), 	TEXT("331"), 		TEXT("0.045"), 	TEXT("163"), 	TEXT("149")}, 																																																																																																																																																																																																																																																							
		{TEXT("36"), 	TEXT("0.005"), 		TEXT("25"), 		TEXT("13200"), 	TEXT("415"), 		TEXT("0.036"), 	TEXT("182"), 	TEXT("167")}, 																																																																																																																																																																																																																																																							
		{TEXT("37"), 	TEXT("0.0045"), 	TEXT("20.2"), 	TEXT("16300"), 	TEXT("512"), 		TEXT("0.029"), 	TEXT("202"), 	TEXT("183")}, 																																																																																																																																																																																																																																																							
		{TEXT("38"), 	TEXT("0.004"), 		TEXT("16"), 		TEXT("20600"), 	TEXT("648"), 		TEXT("0.023"), 	TEXT("225"), 	TEXT("206")}, 																																																																																																																																																																																																																																																							
		{TEXT("39"), 	TEXT("0.0035"), 	TEXT("12.2"), 	TEXT("27000"), 	TEXT("847"), 		TEXT("0.017"), 	TEXT("260"), 	TEXT("235")}, 																																																																																																																																																																																																																																																							
		{TEXT("40"), 	TEXT("0.0031"), 	TEXT("9.61"), 	TEXT("34400"), 	TEXT("1080"), 	TEXT("0.014"), 	TEXT("290"), 	TEXT("263")}, 																																																																																																																																																																																																																																																							
		{TEXT("41"), 	TEXT("0.0028"), 	TEXT("7.84"), 	TEXT("42100"), 	TEXT("1320"), 	TEXT("0.011"), 	TEXT("323"), 	TEXT("294")}, 																																																																																																																																																																																																																																																							
		{TEXT("42"), 	TEXT("0.0025"), 	TEXT("6.25"), 	TEXT("52900"), 	TEXT("1660"), 	TEXT("0.0089"), TEXT("357"), 	TEXT("328")}, 																																																																																																																																																																																																																																																							
		{TEXT("43"), 	TEXT("0.0022"), 	TEXT("4.84"), 	TEXT("68300"), 	TEXT("2140"), 	TEXT("0.0069"), TEXT("408"), 	TEXT("370")}, 																																																																																																																																																																																																																																																							
		{TEXT("44"), 	TEXT("0.002"), 		TEXT("4"), 			TEXT("82600"), 	TEXT("2590"), 	TEXT("0.0057"), TEXT("444"), 	TEXT("400")}, 																																																																																																																																																																																																																																																							
		{TEXT("45"), 	TEXT("0.00176"), 	TEXT("3.1"), 		TEXT("107000"), TEXT("3350"), 	TEXT("0.0044"), TEXT("520"), 	TEXT("465")}, 
		{TEXT("46"), 	TEXT("0.00157"), 	TEXT("2.46"), 	TEXT("134000"), TEXT("4210"), 	TEXT("0.0035"), TEXT("580"), 	TEXT("510")}, 
		{TEXT("47"), 	TEXT("0.0014"), 	TEXT("1.96"), 	TEXT("169000"), TEXT("5290"), 	TEXT("0.0028"), TEXT("630"), 	TEXT("560")}, 
		{TEXT("48"), 	TEXT("0.00124"), 	TEXT("1.54"), 	TEXT("215000"), TEXT("6750"), 	TEXT("0.0022"), TEXT("710"), 	TEXT("645")}, 
		{TEXT("49"), 	TEXT("0.00111"), 	TEXT("1.23"), 	TEXT("268000"), TEXT("8420"), 	TEXT("0.0018"), TEXT("800"), 	TEXT("720")}, 
		{TEXT("50"), 	TEXT("0.00099"), 	TEXT("0.98"), 	TEXT("337000"), TEXT("10600"), 	TEXT("0.0014"), TEXT("880"), 	TEXT("780")}, 
		{TEXT("51"), 	TEXT("0.00088"), 	TEXT("0.774"), 	TEXT("427000"), TEXT("13400"), 	TEXT("0.0011"), TEXT("970"), 	TEXT("855")}, 
		{TEXT("52"), 	TEXT("0.00078"), 	TEXT("0.608"), 	TEXT("543000"), TEXT("17000"), 	TEXT("0.00087"),TEXT("1080"), TEXT("935")}, 
		{TEXT("53"), 	TEXT("0.0007"), 	TEXT("0.49"), 	TEXT("674000"), TEXT("21200"), 	TEXT("0.0007"), TEXT("1270"), TEXT("1110")}, 
		{TEXT("54"), 	TEXT("0.00062"), 	TEXT("0.384"), 	TEXT("859000"), TEXT("27000"), 	TEXT("0.00055"),TEXT("1430"), TEXT("1220")}, 
		{TEXT("55"), 	TEXT("0.00055"), 	TEXT("0.302"), 	TEXT("1090000"),TEXT("34300"), 	TEXT("0.00043"),TEXT("1560"), TEXT("1330")}, 
		{TEXT("56"), 	TEXT("0.00049"), 	TEXT("0.24"), 	TEXT("1380000"),TEXT("43200"), 	TEXT("0.00034"),TEXT("1690"), TEXT("1450")}, 
		{TEXT("57"), 	TEXT("0.000438"), TEXT("0.192"), 	TEXT("1722000"),TEXT("54100"), 	TEXT("0.00027"),TEXT("1960"), TEXT("-")}, 
		{TEXT("58"), 	TEXT("0.00039"), 	TEXT("0.152"), 	TEXT("2166000"),TEXT("68000"), 	TEXT("0.00022"),TEXT("2160"), TEXT("-")}, 
		{TEXT("59"), 	TEXT("0.000347"), TEXT("0.121"), 	TEXT("2737000"),TEXT("85900"), 	TEXT("0.00017"),TEXT("2450"), TEXT("-")}, 
		{TEXT("60"), 	TEXT("0.000309"), TEXT("0.09"), 	TEXT("3453000"),TEXT("108400"),	TEXT("0.00014"),TEXT("2740"), TEXT("-")} 
	};