//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FontTest.rc
//
#define IDS_TITLE                       1
#define IDS_WINDOWCLASS                 3
#define IDI_ICON                        104
#define IDR_BROADWAY                    296
#define IDR_JULIE                       297
#define IDR_SCRAWL                      298
#define IDR_20S                         300
#define IDR_8X14                        301
#define IDR_9X16SMSF                    302
#define IDR_AMBASSAD                    303
#define IDR_ANTIQUE                     304
#define IDR_APEAUS                      305
#define IDR_APLS10                      306
#define IDR_APLS20                      307
#define IDR_ARMENIAN                    308
#define IDR_ART                         309
#define IDR_ASCIIHX                     310
#define IDR_BACKSLNT                    311
#define IDR_BAUHAUS                     312
#define IDR_BIG                         313
#define IDR_BIGSERIF                    314
#define IDR_BINARY                      315
#define IDR_BLOCK                       316
#define IDR_BLOODY                      317
#define IDR_BODONI                      318
#define IDR_BOLD                        319
#define IDR_BOLD0                       320
#define IDR_BOLD1                       321
#define IDR_BOLD2                       322
#define IDR_BOLD3                       323
#define IDR_BOLD4                       324
#define IDR_BOLD5                       325
#define IDR_BOX                         326
#define IDR_BOXROUND                    327
#define IDR_BRAILLE                     328
#define IDR_BROADWY1                    329
#define IDR_BROADWY2                    330
#define IDR_BROADWY3                    331
#define IDR_BROADWY4                    332
#define IDR_BRUSH                       333
#define IDR_CALCULAT                    334
#define IDR_CAPITAL                     335
#define IDR_CAPS                        336
#define IDR_CIRCLE                      337
#define IDR_CNTDOWN                     338
#define IDR_COMPUTR1                    339
#define IDR_COMPUTR2                    340
#define IDR_COMPUTR3                    341
#define IDR_COMPUTR4                    342
#define IDR_COURIER1                    343
#define IDR_COURIER2                    344
#define IDR_CP111                       345
#define IDR_CP112                       346
#define IDR_CP113                       347
#define IDR_CP437                       348
#define IDR_CP850                       349
#define IDR_CP851                       350
#define IDR_CP853                       351
#define IDR_CP860                       352
#define IDR_CP861                       353
#define IDR_CP862                       354
#define IDR_CP863                       355
#define IDR_CP864                       356
#define IDR_CP865                       357
#define IDR_CP866                       358
#define IDR_CP880                       359
#define IDR_CP881                       360
#define IDR_CP882                       361
#define IDR_CP883                       362
#define IDR_CP884                       363
#define IDR_CP885                       364
#define IDR_CPP852                      365
#define IDR_CYRILL1                     366
#define IDR_CYRILL2                     367
#define IDR_CYRILL3                     368
#define IDR_CYRILL4                     369
#define IDR_CYRILL5                     370
#define IDR_CYRILL6                     371
#define IDR_DECORATE                    372
#define IDR_DEFAULT                     373
#define IDR_DONNA                       375
#define IDR_ELEGAND3                    376
#define IDR_ELEGANT1                    377
#define IDR_ELEGANT2                    378
#define IDR_ELERGON                     379
#define IDR_EZVGA1                      380
#define IDR_EZVGA2                      381
#define IDR_FE8X16                      382
#define IDR_FLORI                       383
#define IDR_FRESNO                      384
#define IDR_FUTURE                      385
#define IDR_FYVUSH                      386
#define IDR_GAELIC                      387
#define IDR_GOTHIC1                     388
#define IDR_GOTHIC2                     389
#define IDR_GOTHNEW                     390
#define IDR_GRCKSSRF                    391
#define IDR_GREEK                       392
#define IDR_HACK4TH                     393
#define IDR_HANDUGLY                    394
#define IDR_HANDWRIT                    395
#define IDR_HEARST                      396
#define IDR_HEB7BIT                     397
#define IDR_HEBBOLD1                    398
#define IDR_HEBBOLD2                    399
#define IDR_HEBKTAV1                    400
#define IDR_HEBKTAV2                    401
#define IDR_HEBLARGE                    402
#define IDR_HEBREW                      403
#define IDR_HEBUGLY                     404
#define IDR_HEBYOG1                     405
#define IDR_HELV1                       406
#define IDR_HELV2                       407
#define IDR_IBM                         408
#define IDR_ITALIC1                     409
#define IDR_ITALIC2                     410
#define IDR_ITALIC3                     411
#define IDR_JULIE1                      412
#define IDR_JULIE2                      413
#define IDR_KANA                        414
#define IDR_KING                        415
#define IDR_KNIGHT                      416
#define IDR_KOOL                        417
#define IDR_LBITALIC                    418
#define IDR_LBLARGE                     419
#define IDR_LBOCR                       420
#define IDR_LCD                         421
#define IDR_LEGEND                      422
#define IDR_LITE                        423
#define IDR_MACNTOSH                    424
#define IDR_MEDIEVIL                    425
#define IDR_MERP                        426
#define IDR_MERP1                       427
#define IDR_MERP2                       428
#define IDR_MODERN1                     429
#define IDR_MODERN2                     430
#define IDR_MODERN3                     431
#define IDR_MODERN4                     432
#define IDR_MODERN5                     433
#define IDR_MORSE                       434
#define IDR_NUTSO                       435
#define IDR_OLDENG1                     436
#define IDR_OLDENG2                     437
#define IDR_OLDENG3                     438
#define IDR_OLDENG4                     439
#define IDR_OLDENG5                     440
#define IDR_OLDENG6                     441
#define IDR_ORATOR                      442
#define IDR_OUTLINE                     443
#define IDR_PARKAVE                     444
#define IDR_PEKIGORD                    445
#define IDR_PERCY                       446
#define IDR_PERSIAN                     447
#define IDR_POLICE                      448
#define IDR_POOTER                      449
#define IDR_PPROMAN                     450
#define IDR_PPSSER                      451
#define IDR_PRESTIG1                    452
#define IDR_PRESTIG2                    453
#define IDR_READABL1                    454
#define IDR_READABL2                    455
#define IDR_READABL3                    456
#define IDR_REVERSE                     457
#define IDR_ROMAN1                      458
#define IDR_ROMAN2                      459
#define IDR_ROMAN3                      460
#define IDR_ROMAN4                      461
#define IDR_ROMANY                      462
#define IDR_ROYAL                       463
#define IDR_RUNES                       464
#define IDR_RUSSIAN                     465
#define IDR_SANSERF1                    466
#define IDR_SANSERF2                    467
#define IDR_SANSERF3                    468
#define IDR_SCRAWL1                     469
#define IDR_SCRAWL2                     470
#define IDR_SCRAWL3                     471
#define IDR_SCRAWL4                     472
#define IDR_SCRAWL5                     473
#define IDR_SCRIPT1                     474
#define IDR_SCRIPT2                     475
#define IDR_SCRIPT3                     476
#define IDR_SCRIPT4                     477
#define IDR_SERIF                       478
#define IDR_SERIFBIG                    479
#define IDR_SHADE                       480
#define IDR_SIGGLY                      481
#define IDR_SIMPAGAR                    482
#define IDR_SIMPLE                      483
#define IDR_SLANT                       484
#define IDR_SMALL                       485
#define IDR_SMOOTH                      486
#define IDR_SMVGA                       487
#define IDR_SPRANT01                    488
#define IDR_SPRANTO1                    489
#define IDR_SPRANTO2                    490
#define IDR_SQUARE                      491
#define IDR_STANDARD                    492
#define IDR_STRETCH                     493
#define IDR_SUBSCR1                     494
#define IDR_SUBSCR2                     495
#define IDR_SUBSUP                      496
#define IDR_SUPER                       497
#define IDR_SUPSCR1                     498
#define IDR_SUPSCR2                     499
#define IDR_SWISS1                      500
#define IDR_SWISS2                      501
#define IDR_SWISS3                      502
#define IDR_SWISSAV1                    503
#define IDR_SWISSAV2                    504
#define IDR_SWISSAV3                    505
#define IDR_SWISSBX1                    506
#define IDR_SWISSBX2                    507
#define IDR_TALLTHIN                    508
#define IDR_TENGWAR                     509
#define IDR_TEXMATH                     510
#define IDR_THAI                        511
#define IDR_THICK                       512
#define IDR_THIN                        513
#define IDR_THINSS                      514
#define IDR_THNSERIF                    515
#define IDR_TINY                        516
#define IDR_TTHINSS                     517
#define IDR_UNDERLIN                    518
#define IDR_VGAROM                      519
#define IDR_VOGUE                       520
#define IDR_VOYNICH                     521
#define IDR_WACKY                       522
#define IDR_WEIRD                       523
#define IDR_WIGGLY                      524
#define IDR_YIDDISH                     525

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        299
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
