//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Electro.rc
//
#define IDI_APP_ICON                    101
#define IDM_MENU                        102
#define IDD_ABOUT                       104
#define IDD_CHIP_REFERENCE              105
#define IDB_ABOUTPIC                    106
#define IDD_RESISTOR_COLOR_CODE         106
#define IDD_METAL_ALLOY_RESISTANCES     107
#define IDD_RESONANCE                   109
#define IDD_DIALECTRIC_CONSTANTS        110
#define IDD_REACTANCE                   111
#define IDD_DC_OHMS_LAW                 112
#define IDD_REACTANCE_INDUCTIVE         113
#define IDD_REACTANCE_CAPACITIVE        114
#define IDD_CHIP_REFERENCE_SELECTION    115
#define IDD_CHIP_REFERENCE_FUNCTION_TABLE 116
#define IDD_CHIP_REFERENCE_PINOUT       117
#define IDD_SCHEMATIC_SYMBOLS           118
#define IDD_RCICALC                     119
#define IDD_RCICALC_RESISTANCE          120
#define IDD_RCICALC_CAPACITANCE         121
#define IDD_RCICALC_INDUCTANCE          122
#define IDD_CITIZENS_BAND               123
#define IDD_ENERGY_STORED_INDUCTOR      124
#define IDD_ENERGY_STORED_CAPACITOR     125
#define IDD_ENERGY_STORED               126
#define IDD_IMPEDANCE                   127
#define IDD_THREE_PHASE_POWER           128
#define IDD_COMMON_CONNECTORS           129
#define IDD_TV_CHANNELS                 130
#define IDD_COPPER_WIRE                 131
#define IDD_DW_TRANSFORMS               132
#define IDB_RES_BAND_BLACK              133
#define IDD_KFACTORS                    133
#define IDB_RES_LEFT                    134
#define IDD_OPAMPS                      134
#define IDB_RES_BAND_NONE               137
#define IDD_MORSE_CODE                  137
#define IDB_RES_BAND_BROWN              138
#define IDD_RADIO_FREQUENCY_SPECTRUM    138
#define IDB_RES_BAND_GOLD               139
#define IDD_TIMER555_MONOSTABLE         139
#define IDB_RES_BAND_GREEN              140
#define IDD_TIMER555_ASTABLE            140
#define IDB_RES_BAND_GREY               141
#define IDD_TIMER555                    141
#define IDB_RES_BAND_BLUE               142
#define IDB_RES_BAND_YELLOW             143
#define IDB_RES_BAND_RED                144
#define IDB_RES_BAND_SILVER             145
#define IDB_RES_BAND_VIOLET             146
#define IDB_RES_BAND_WHITE              147
#define IDB_RES_BAND_ORANGE             148
#define IDB_RES_RIGHT                   149
#define IDB_RES_SPACER                  150
#define IDB_TITLEPIC                    151
#define IDB_BLUELINE                    152
#define IDB_CHIP_14                     154
#define IDI_SCHEM_AMMETER               160
#define IDI_SCHEM_AND_GATE              161
#define IDI_SCHEM_ANTENNA_BALANCED      162
#define IDI_SCHEM_ANTENNA_GENERAL1      163
#define IDI_SCHEM_ANTENNA_GENERAL2      164
#define IDI_SCHEM_ANTENNA_LOOP_SHIELDED 165
#define IDI_SCHEM_ANTENNA_LOOP_UNSHIELDED 166
#define IDI_SCHEM_ANTENNA_UNBALANCED1   167
#define IDI_SCHEM_ANTENNA_UNBALANCED2   168
#define IDI_SCHEM_ATTENUATOR_FIXED      169
#define IDI_SCHEM_ATTENUATOR_VARIABLE   170
#define IDI_SCHEM_BATTERY               171
#define IDI_SCHEM_CAPACITOR_FEEDTHROUGH 172
#define IDI_SCHEM_CAPACITOR_FIXED_NOPOLES 173
#define IDI_SCHEM_CAPACITOR_FIXED_POLES 174
#define IDI_SCHEM_CAPACITOR_GANGED_VARIABLE 175
#define IDI_SCHEM_CAPACITOR_GENERAL     176
#define IDI_SCHEM_CAPACITOR_VARIABLE_SINGLE 177
#define IDI_SCHEM_CAPACITOR_VARIABLE_SPLIT_STATOR 178
#define IDI_SCHEM_CATHODE_COLD          179
#define IDI_SCHEM_CATHODE_DIRECTLY_HEATED 180
#define IDI_SCHEM_CATHODE_INDIRECTLY_HEATED1 181
#define IDI_SCHEM_CATHODE_INDIRECTLY_HEATED2 182
#define IDI_SCHEM_CAVITY_RESONATOR      183
#define IDI_SCHEM_CELL                  184
#define IDI_SCHEM_CIRCUIT_BREAKER       185
#define IDI_SCHEM_COAXIAL_CABLE1        186
#define IDI_SCHEM_COAXIAL_CABLE2        187
#define IDI_SCHEM_CRYSTAL_PIEZOELECTRIC 188
#define IDI_SCHEM_DELAY_LINE1           189
#define IDI_SCHEM_DELAY_LINE2           190
#define IDI_SCHEM_DIODE_GENERAL         191
#define IDI_SCHEM_DIODE_GUNN            192
#define IDI_SCHEM_DIODE_LIGHT_EMITTING  193
#define IDI_SCHEM_DIODE_PHOTOSENSITIVE  194
#define IDI_SCHEM_DIODE_PHOTOVOLTAIC    195
#define IDI_SCHEM_DIODE_PIN             196
#define IDI_SCHEM_DIODE_VARACTOR        197
#define IDB_SPLASH_SCREEN               197
#define IDI_SCHEM_DIODE_ZENER           198
#define IDI_SCHEM_DIRECTIONAL_COUPLER1  199
#define IDI_SCHEM_DIRECTIONAL_COUPLER2  200
#define IDI_SCHEM_EXCLUSIVE_OR_GATE     201
#define IDI_SCHEM_FEMALE_CONTACT_GENERAL 202
#define IDB_DELTA                       202
#define IDI_SCHEM_FERRITE_BEAD1         203
#define IDB_WYE                         203
#define IDI_SCHEM_FERRITE_BEAD2         204
#define IDB_DELTA_TRANSFORM             204
#define IDI_SCHEM_FUSE1                 205
#define IDB_WYE_TRANSFORM               205
#define IDI_SCHEM_FUSE2                 206
#define IDB_TOOLBAR_ICONS               206
#define IDI_SCHEM_GALVANOMETER1         207
#define IDR_MORSECODE_0                 207
#define IDI_SCHEM_GALVANOMETER2         208
#define IDR_MORSECODE_Z                 208
#define IDI_SCHEM_GROUND_CHASSIS1       209
#define IDR_MORSECODE_2                 209
#define IDI_SCHEM_GROUND_CHASSIS2       210
#define IDR_MORSECODE_3                 210
#define IDI_SCHEM_GROUND_EARTH          211
#define IDR_MORSECODE_4                 211
#define IDI_SCHEM_HANDSET               212
#define IDR_MORSECODE_5                 212
#define IDI_SCHEM_HEADPHONE_DOUBLE      213
#define IDR_MORSECODE_6                 213
#define IDI_SCHEM_HEADPHONE_SINGLE      214
#define IDR_MORSECODE_7                 214
#define IDI_SCHEM_INDUCTOR_AIR_CORE     215
#define IDR_MORSECODE_8                 215
#define IDI_SCHEM_INDUCTOR_BIFILAR      216
#define IDR_MORSECODE_9                 216
#define IDI_SCHEM_INDUCTOR_IRON_CORE    217
#define IDR_MORSECODE_A                 217
#define IDI_SCHEM_INDUCTOR_TAPPED       218
#define IDR_MORSECODE_B                 218
#define IDI_SCHEM_INDUCTOR_VARIABLE1    219
#define IDR_MORSECODE_C                 219
#define IDI_SCHEM_INDUCTOR_VARIABLE2    220
#define IDR_MORSECODE_D                 220
#define IDI_SCHEM_INTEGRATED_CIRCUIT    221
#define IDR_MORSECODE_E                 221
#define IDI_SCHEM_INVERTER              222
#define IDR_MORSECODE_F                 222
#define IDI_SCHEM_JACK_COAXIAL          223
#define IDR_MORSECODE_G                 223
#define IDI_SCHEM_JACK_PHONE_2CONDUCTOR 224
#define IDR_MORSECODE_H                 224
#define IDI_SCHEM_JACK_PHONE_2CONDUCTOR_INTERRUPTING 225
#define IDR_MORSECODE_I                 225
#define IDI_SCHEM_JACK_PHONE_3CONDUCTOR 226
#define IDR_MORSECODE_J                 226
#define IDI_SCHEM_JACK_PHONO            227
#define IDR_MORSECODE_K                 227
#define IDI_SCHEM_KEY_TELEGRAPH         228
#define IDR_MORSECODE_L                 228
#define IDI_SCHEM_LAMP_INCANDESCENT     229
#define IDR_MORSECODE_M                 229
#define IDI_SCHEM_LAMP_NEON             230
#define IDR_MORSECODE_N                 230
#define IDI_SCHEM_MALE_CONTACT_GENERAL  231
#define IDR_MORSECODE_O                 231
#define IDI_SCHEM_MICROPHONE            232
#define IDR_MORSECODE_P                 232
#define IDI_SCHEM_NAND_GATE             233
#define IDR_MORSECODE_Q                 233
#define IDI_SCHEM_NEGATIVE_VOLTAGE_CONNECTION 234
#define IDR_MORSECODE_R                 234
#define IDI_SCHEM_NOR_GATE              235
#define IDR_MORSECODE_S                 235
#define IDI_SCHEM_OPERATIONAL_AMPLIFIER 236
#define IDR_MORSECODE_T                 236
#define IDI_SCHEM_OR_GATE               237
#define IDR_MORSECODE_U                 237
#define IDI_SCHEM_OUTLET_UTILITY_117_V  238
#define IDR_MORSECODE_V                 238
#define IDI_SCHEM_OUTLET_UTILITY_234_V  239
#define IDR_MORSECODE_W                 239
#define IDI_SCHEM_PHOTOCELL_TUBE        240
#define IDR_MORSECODE_Y                 240
#define IDI_SCHEM_PLUG_PHONE_2CONDUCTOR 241
#define IDR_MORSECODE_X                 241
#define IDI_SCHEM_PLUG_PHONE_3CONDUCTOR 242
#define IDR_MORSECODE_1                 242
#define IDI_SCHEM_PLUG_PHONO            243
#define IDB_OPAMP_VOLTAGE_FOLLOWER      243
#define IDI_SCHEM_PLUG_UTILITY_117_V    244
#define IDB_OPAMP_DIFFERENTIAL_INPUT_AMPLIFIER 244
#define IDI_SCHEM_PLUG_UTILITY_234_V    245
#define IDB_OPAMP_DIFFERENTIATING_INPUT_AMPLIFIER 245
#define IDI_SCHEM_POSITIVE_VOLTAGE_CONNECTION 246
#define IDB_OPAMP_INVERTING_AMPLIFIER   246
#define IDI_SCHEM_POTENTIOMETER1        247
#define IDB_OPAMP_NONINVERTING_AMPLIFIER 247
#define IDI_SCHEM_POTENTIOMETER2        248
#define IDB_OPAMP_ADDING_SUBTRACTING_SCALING_AMPLIFIER 248
#define IDI_SCHEM_PROBE_RADIO_FREQUENCY 249
#define IDR_MORSECODE_SPACE             249
#define IDI_SCHEM_RECTIFIER_SEMICONDUCTOR 250
#define IDR_MORSECODE_COLON             250
#define IDI_SCHEM_RECTIFIER_SILICON_CONTROLLED 251
#define IDR_MORSECODE_COMMA             251
#define IDI_SCHEM_RECTIFIER_TUBE_TYPE   252
#define IDR_MORSECODE_HYPHEN            252
#define IDI_SCHEM_RELAY_DPDT            253
#define IDR_MORSECODE_PARENTHESES       253
#define IDI_SCHEM_RELAY_DPST            254
#define IDR_MORSECODE_PERIOD            254
#define IDI_SCHEM_RELAY_SPDT            255
#define IDR_MORSECODE_QUESTIONMARK      255
#define IDI_SCHEM_RELAY_SPST            256
#define IDR_MORSECODE_QUOTES            256
#define IDI_SCHEM_RESISTOR              257
#define IDR_MORSECODE_APOSTROPHE        257
#define IDI_SCHEM_RESONATOR             258
#define IDB_TELEGRAPH                   258
#define IDI_SCHEM_RHEOSTAT1             259
#define IDB_NULLIMAGE                   259
#define IDI_SCHEM_RHEOSTAT2             260
#define IDB_MONOSTABLE                  260
#define IDI_SCHEM_SATURABLE_REACTOR     261
#define IDB_ASTABLE                     261
#define IDI_SCHEM_SHIELDING             262
#define IDI_SCHEM_SIGNAL_GENERATOR      263
#define IDI_SCHEM_SPEAKER1              264
#define IDI_SCHEM_SPEAKER2              265
#define IDI_SCHEM_SWITCH_DPDT           266
#define IDI_SCHEM_SWITCH_DPST           267
#define IDI_SCHEM_SWITCH_MOMENTARY      268
#define IDI_SCHEM_SWITCH_ROTARY         269
#define IDI_SCHEM_SWITCH_SPDT           270
#define IDI_SCHEM_SWITCH_SPST           271
#define IDI_SCHEM_TERMINALS_BALANCED    272
#define IDI_SCHEM_TERMINALS_UNBALANCED  273
#define IDI_SCHEM_TEST_POINT            274
#define IDI_SCHEM_THERMOCOUPLE1         275
#define IDI_SCHEM_THERMOCOUPLE2         276
#define IDI_SCHEM_THYRISTOR             277
#define IDI_SCHEM_TRANSFORMER_AIR_CORE  278
#define IDI_SCHEM_TRANSFORMER_IRON_CORE 279
#define IDI_SCHEM_TRANSFORMER_TAPPED_PRIMARY 280
#define IDI_SCHEM_TRANSFORMER_TAPPED_SECONDARY 281
#define IDI_SCHEM_TRANSISTOR_BIPOLAR_NPN 282
#define IDI_SCHEM_TRANSISTOR_BIPOLAR_PNP 283
#define IDI_SCHEM_TRANSISTOR_FIELD_EFFECT_NCHANNEL 284
#define IDI_SCHEM_TRANSISTOR_FIELD_EFFECT_PCHANNEL 285
#define IDI_SCHEM_TRANSISTOR_METAL_OXIDE_DUALGATE 286
#define IDI_SCHEM_TRANSISTOR_METAL_OXIDE_SINGLEGATE 287
#define IDI_SCHEM_TRANSISTOR_PHOTOSENSITIVE 288
#define IDI_SCHEM_TRANSISTOR_UNIJUNCTION 289
#define IDI_SCHEM_TUBE_DIODE            290
#define IDI_SCHEM_TUBE_PENTODE          291
#define IDI_SCHEM_TUBE_PHOTOMULTIPLIER  292
#define IDI_SCHEM_TUBE_TETRODE          293
#define IDI_SCHEM_TUBE_TRIODE           294
#define IDI_SCHEM_UNSPECIFIED_COMPONENT 295
#define IDI_SCHEM_VOLTMETER             296
#define IDI_SCHEM_WATTMETER1            297
#define IDI_SCHEM_WATTMETER2            298
#define IDI_SCHEM_WIRES                 299
#define IDI_SCHEM_WIRES_CONNECTED_CROSSING1 300
#define IDI_SCHEM_WIRES_CONNECTED_CROSSING2 301
#define IDI_SCHEM_WIRES_NOT_CONNECTED_CROSSING1 302
#define IDI_SCHEM_WIRES_NOT_CONNECTED_CROSSING2 303
#define IDB_CENTRONICS_36_FEMALE        400
#define IDB_CENTRONICS_36_MALE          401
#define IDB_CENTRONICS_50_FEMALE        402
#define IDB_CENTRONICS_50_MALE          403
#define IDB_COAX_FEMALE                 404
#define IDB_COAX_MALE                   405
#define IDB_DB25_FEMALE                 406
#define IDB_DB25_MALE                   407
#define IDB_DB37_FEMALE                 408
#define IDB_DB37_MALE                   409
#define IDB_DB50_FEMALE                 410
#define IDB_DB50_MALE                   411
#define IDB_DB9_FEMALE                  412
#define IDB_DB9_MALE                    413
#define IDB_FIBER_GUIDE_FDDI            414
#define IDB_FIBER_GUIDE_SC              415
#define IDB_FIBER_GUIDE_ST              416
#define IDB_FLAT_RIBBON_50_POSITION_EDGE_SOCKET 417
#define IDB_FLAT_RIBBON_IDC_50_POSITION_SOCKET 418
#define IDB_HIGH_DENSITY_DB15_FEMALE    419
#define IDB_HIGH_DENSITY_DB15_MALE      420
#define IDB_INFOPORT_SERIES_I           421
#define IDB_INFOPORT_SERIES_II          422
#define IDB_INFOPORT_SERIES_III_KEYING_OPTION_1 423
#define IDB_INFOPORT_SERIES_III_KEYING_OPTION_2 424
#define IDB_INFOPORT_SERIES_III_KEYING_OPTION_3 425
#define IDB_INFOPORT_SERIES_III_KEYING_OPTION_4 426
#define IDB_MINI_CENTRONICS_36_FEMALE   427
#define IDB_MINI_CENTRONICS_36_MALE     428
#define IDB_MINI_CENTRONICS_50_FEMALE   429
#define IDB_MINI_CENTRONICS_50_MALE     430
#define IDB_MINI_CENTRONICS_60_FEMALE   431
#define IDB_MINI_CENTRONICS_60_MALE     432
#define IDB_MINI_DB_50_FEMALE           433
#define IDB_MINI_DB_50_MALE             434
#define IDB_MINI_DB68_FEMALE            435
#define IDB_MINI_DB68_MALE              436
#define IDB_MODULAR_DEC_6P6C            437
#define IDB_MODULAR_RJ11_6P4C           438
#define IDB_MODULAR_RJ12_6P6C           439
#define IDB_MODULAR_RJ45                440
#define IDB_MONITOR_POWER_ADAPTER       441
#define IDB_POWER_CORD                  442
#define IDB_POWER_EXTENSION_CORD        443
#define IDB_SCSI_CONNECTOR_VHDCI        444
#define IDC_EDIT_I                      1006
#define IDC_VERSION                     1006
#define IDC_EDIT_R                      1007
#define IDC_DIALOG_TITLE                1008
#define IDC_CALCULATE                   1009
#define IDC_CLEAR                       1011
#define IDC_EDIT_P                      1012
#define IDC_RESULTS2                    1012
#define IDC_RESULTS1                    1013
#define IDC_EDIT_C                      1017
#define IDC_LISTVIEW                    1019
#define IDC_EDIT_X                      1022
#define IDC_EDIT_E                      1024
#define IDC_BAND_1                      1025
#define IDC_BAND_2                      1026
#define IDC_BAND_3                      1027
#define IDC_BAND_4                      1028
#define IDC_CHIP_DESCRIPTION            1029
#define IDC_CHIP_REFERENCE_LISTBOX      1033
#define IDC_PIN1                        1036
#define IDC_PIN2                        1037
#define IDC_PIN3                        1038
#define IDC_PIN4                        1039
#define IDC_PIN5                        1040
#define IDC_PIN6                        1041
#define IDC_PIN7                        1042
#define IDC_PIN8                        1043
#define IDC_PIN9                        1044
#define IDC_PIN10                       1045
#define IDC_BANDCOLOR_1                 1046
#define IDC_PIN11                       1046
#define IDC_BANDCOLOR_2                 1047
#define IDC_PIN12                       1047
#define IDC_BANDCOLOR_3                 1048
#define IDC_PIN13                       1048
#define IDC_BANDCOLOR_4                 1049
#define IDC_PIN14                       1049
#define IDC_CHIP_DETAIL_TITLE           1052
#define IDC_EDIT_L                      1053
#define IDC_EDIT_F                      1054
#define IDC_FT_COL_1_HEAD               1054
#define IDC_FT_COL_2_HEAD               1055
#define IDC_FT_COL_3_HEAD               1056
#define IDC_FT_COL_4_HEAD               1057
#define IDC_FT_COL_5_HEAD               1058
#define IDC_FT_COL_6_HEAD               1059
#define IDC_EDIT_TH                     1059
#define IDC_FT_COL_7_HEAD               1060
#define IDC_EDIT_TL                     1060
#define IDC_FT_ROW_1_1                  1061
#define IDC_EDIT_T                      1061
#define IDC_FT_ROW_1_2                  1062
#define IDC_FT_ROW_1_3                  1063
#define IDC_FT_ROW_1_4                  1064
#define IDC_FT_ROW_1_5                  1065
#define IDC_FT_ROW_1_6                  1066
#define IDC_FT_ROW_1_7                  1067
#define IDC_FT_ROW_2_1                  1068
#define IDC_FT_ROW_2_2                  1069
#define IDC_FT_ROW_2_3                  1070
#define IDC_FT_ROW_2_4                  1071
#define IDC_FT_ROW_2_5                  1072
#define IDC_FT_ROW_2_6                  1073
#define IDC_FT_ROW_2_7                  1074
#define IDC_FT_ROW_3_1                  1075
#define IDC_FT_ROW_3_2                  1076
#define IDC_FT_ROW_3_3                  1077
#define IDC_FT_ROW_3_4                  1078
#define IDC_FT_ROW_3_5                  1079
#define IDC_FT_ROW_3_6                  1080
#define IDC_FT_ROW_3_7                  1081
#define IDC_FT_ROW_4_1                  1082
#define IDC_FT_ROW_4_2                  1083
#define IDC_FT_ROW_4_3                  1084
#define IDC_FT_ROW_4_4                  1085
#define IDC_FT_ROW_4_5                  1086
#define IDC_FT_ROW_4_6                  1087
#define IDC_FT_ROW_4_7                  1088
#define IDC_FT_ROW_5_1                  1089
#define IDC_FT_ROW_5_2                  1090
#define IDC_FT_ROW_5_3                  1091
#define IDC_FT_ROW_5_4                  1092
#define IDC_FT_ROW_5_5                  1093
#define IDC_FT_ROW_5_6                  1094
#define IDC_FT_ROW_5_7                  1095
#define IDC_FT_ROW_6_1                  1096
#define IDC_FT_ROW_6_2                  1097
#define IDC_FT_ROW_6_3                  1098
#define IDC_FT_ROW_6_4                  1099
#define IDC_FT_ROW_6_5                  1100
#define IDC_FT_ROW_6_6                  1101
#define IDC_FT_ROW_6_7                  1102
#define IDC_FT_ROW_7_1                  1103
#define IDC_FT_ROW_7_2                  1104
#define IDC_FT_ROW_7_3                  1105
#define IDC_FT_ROW_7_4                  1106
#define IDC_FT_ROW_7_5                  1107
#define IDC_FT_ROW_7_6                  1108
#define IDC_FT_ROW_7_7                  1109
#define IDC_FT_ROW_8_1                  1110
#define IDC_FT_ROW_8_2                  1111
#define IDC_FT_ROW_8_3                  1112
#define IDC_FT_ROW_8_4                  1113
#define IDC_FT_ROW_8_5                  1114
#define IDC_FT_ROW_8_6                  1115
#define IDC_FT_ROW_8_7                  1116
#define IDC_TABS                        1117
#define IDC_EDIT_R1                     1126
#define IDC_EDIT_R2                     1127
#define IDC_EDIT_RA                     1129
#define IDC_SERIAL                      1130
#define IDC_PARALLEL                    1131
#define IDC_VALUES                      1133
#define IDC_ADD                         1134
#define IDC_NEW_VALUE                   1135
#define IDC_RESULTS                     1136
#define IDC_REMOVE                      1139
#define IDC_EDIT_W                      1146
#define IDC_EDIT_Z                      1149
#define IDC_PIC_FROM                    1152
#define IDC_PIC_TO                      1153
#define IDC_EDIT_EP                     1154
#define IDC_EDIT_ES                     1155
#define IDC_EDIT_N                      1156
#define IDC_DD_FROM                     1157
#define IDC_EDIT_Z1                     1157
#define IDC_DD_TO                       1158
#define IDC_CONNECTOR                   1158
#define IDC_EDIT_Z2                     1158
#define IDC_IMAGE                       1159
#define IDC_EDIT_Z3                     1159
#define IDC_DW_SWAP                     1161
#define IDC_EDIT_ZA                     1162
#define IDC_EDIT_ZB                     1163
#define IDC_EDIT_ZC                     1164
#define IDC_CONFIGURATION               1165
#define IDC_ENCODE                      1166
#define IDC_EDIT_TEXT                   1167
#define IDC_TELEGRAPH                   1168
#define IDC_TF_SWAP                     1169
#define IDM_HELP                        40004
#define IDM_ABOUT                       40007
#define IDM_TOOLS                       40009
#define IDM_EXIT                        40012
#define IDS_CAP_TOOLS                   40014
#define IDS_CAP_HELP                    40016
#define IDM_CHIP_REFERENCE              40017
#define IDM_RESISTOR_COLOR_CODE         40018
#define IDM_DC_OHMS_LAW                 40021
#define IDM_DIALECTRIC_CONSTANTS        40022
#define IDM_METAL_ALLOY_RESISTANCES     40023
#define IDM_REACTANCE                   40024
#define IDM_RESONANCE                   40025
#define IDM_REFERENCE                   40026
#define IDS_CAP_REFERENCE               40028
#define IDS_VERSION                     40029
#define IDS_APP_TITLE                   40030
#define IDS_APP_CLASS                   40031
#define IDS_INITIALIZING_PLEASE_WAIT    40032
#define IDM_SCHEMATIC_SYMBOLS           40033
#define IDS_COPYRIGHT                   40033
#define IDS_ALL_RIGHTS_RESERVED         40034
#define IDM_RCI_CALC                    40035
#define IDS_PROGRAMMEDBY                40035
#define IDM_CITIZENS_BAND               40036
#define IDS_TITLE_1                     40036
#define IDS_TITLE_2                     40037
#define IDS_TITLE_3                     40038
#define IDM_ENERGY_STORED               40041
#define IDM_IMPEDANCE                   40042
#define IDM_THREE_PHASE_POWER           40043
#define IDM_COMMON_CONNECTORS           40044
#define IDM_TV_CHANNELS                 40045
#define IDM_COPPER_WIRE                 40046
#define IDM_DW_TRANS                    40047
#define IDM_KFACTORS                    40049
#define IDM_OPAMPS                      40050
#define IDM_MORSE_CODE                  40051
#define IDM_RADIO_FREQUENCY_SPECTRUM    40052
#define IDM_TIMER555                    40053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        262
#define _APS_NEXT_COMMAND_VALUE         40054
#define _APS_NEXT_CONTROL_VALUE         1170
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
