//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GXLibTest.rc
//
#define IDS_TITLE                       1
#define IDS_WINDOWCLASS                 3
#define IDI_ICON                        104
#define IDR_WALLS_MOVING_4              205
#define IDR_WALLS_MOVING_1              206
#define IDR_WALLS_MOVING_2_PALETTE      207
#define IDR_WALLS_MOVING_2              208
#define IDR_WALLS_MOVING_3_PALETTE      209
#define IDR_WALLS_MOVING_3              210
#define IDR_WALLS_MOVING_4_PALETTE      211
#define IDR_WALLS_MOVING_1_PALETTE      212
#define IDR_MAX_FPS_TEST_SPRITE_2_PALETTE 217
#define IDR_MAX_FPS_TEST_SPRITE_1_PALETTE 218
#define IDR_MAX_FPS_TEST_SPRITE_1_FRAME_3 219
#define IDR_MAX_FPS_TEST_SPRITE_1_FRAME_2 220
#define IDR_MAX_FPS_TEST_SPRITE_1_FRAME_1 221
#define IDR_MAX_FPS_TEST_SPRITE_2_FRAME_10 223
#define IDR_MAX_FPS_TEST_SPRITE_2_FRAME_1 224
#define IDR_MAX_FPS_TEST_SPRITE_2_FRAME_2 225
#define IDR_MAX_FPS_TEST_SPRITE_2_FRAME_3 226
#define IDR_MAX_FPS_TEST_SPRITE_2_FRAME_4 227
#define IDR_MAX_FPS_TEST_SPRITE_2_FRAME_5 228
#define IDR_MAX_FPS_TEST_SPRITE_2_FRAME_6 229
#define IDR_MAX_FPS_TEST_SPRITE_2_FRAME_7 230
#define IDR_MAX_FPS_TEST_SPRITE_2_FRAME_8 231
#define IDR_MAX_FPS_TEST_SPRITE_2_FRAME_9 232
#define IDR_MAX_FPS_TEST_SPRITE_3_PALETTE 233
#define IDR_MAX_FPS_TEST_SPRITE_3_FRAME_2 234
#define IDR_MAX_FPS_TEST_SPRITE_3_FRAME_1 235
#define IDR_MAX_FPS_TEST_SPRITE_4_PALETTE 236
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_10 237
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_11 238
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_12 239
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_13 240
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_14 241
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_15 242
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_2 243
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_3 244
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_4 245
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_5 246
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_9 247
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_6 248
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_7 249
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_8 250
#define IDR_MAX_FPS_TEST_SPRITE_4_FRAME_1 251
#define IDR_MAX_FPS_TEST_BACKGROUND_PALETTE 298
#define IDR_MAX_FPS_TEST_BACKGROUND     299
#define IDR_GRADIENT                    302
#define IDR_GRADIENT_PALETTE            303
#define IDR_HFLIP                       304
#define IDR_VFLIP                       305
#define IDR_FULLSCREENBOX               306
#define IDR_FULLSCREENBOXPALETTE        307
#define IDR_PICTURE                     308
#define IDR_PICTURE_PALETTE             309
#define IDR_BOX                         326

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        310
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
